package com.huizhi.supplier.db.dao;

import com.huizhi.supplier.db.annotation.MybatisUserInfo;
import com.huizhi.supplier.db.model.TCpyRegistrationRecords;
import com.huizhi.supplier.db.model.TCpyRegistrationRecordsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@MybatisUserInfo
public interface TCpyRegistrationRecordsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_registration_records
     *
     * @mbg.generated
     */
    long countByExample(TCpyRegistrationRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_registration_records
     *
     * @mbg.generated
     */
    int deleteByExample(TCpyRegistrationRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_registration_records
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_registration_records
     *
     * @mbg.generated
     */
    int insert(TCpyRegistrationRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_registration_records
     *
     * @mbg.generated
     */
    int insertSelective(TCpyRegistrationRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_registration_records
     *
     * @mbg.generated
     */
    TCpyRegistrationRecords selectOneByExample(TCpyRegistrationRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_registration_records
     *
     * @mbg.generated
     */
    TCpyRegistrationRecords selectOneByExampleSelective(@Param("example") TCpyRegistrationRecordsExample example, @Param("selective") TCpyRegistrationRecords.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_registration_records
     *
     * @mbg.generated
     */
    List<TCpyRegistrationRecords> selectByExampleSelective(@Param("example") TCpyRegistrationRecordsExample example, @Param("selective") TCpyRegistrationRecords.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_registration_records
     *
     * @mbg.generated
     */
    List<TCpyRegistrationRecords> selectByExample(TCpyRegistrationRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_registration_records
     *
     * @mbg.generated
     */
    TCpyRegistrationRecords selectByPrimaryKeySelective(@Param("id") String id, @Param("selective") TCpyRegistrationRecords.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_registration_records
     *
     * @mbg.generated
     */
    TCpyRegistrationRecords selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_registration_records
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TCpyRegistrationRecords record, @Param("example") TCpyRegistrationRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_registration_records
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TCpyRegistrationRecords record, @Param("example") TCpyRegistrationRecordsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_registration_records
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCpyRegistrationRecords record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_registration_records
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCpyRegistrationRecords record);
}