package com.huizhi.supplier.db.dao;

import com.huizhi.supplier.db.annotation.MybatisUserInfo;
import com.huizhi.supplier.db.model.TCpyPermanentInvestment;
import com.huizhi.supplier.db.model.TCpyPermanentInvestmentExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@MybatisUserInfo
public interface TCpyPermanentInvestmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_permanent_investment
     *
     * @mbg.generated
     */
    long countByExample(TCpyPermanentInvestmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_permanent_investment
     *
     * @mbg.generated
     */
    int deleteByExample(TCpyPermanentInvestmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_permanent_investment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_permanent_investment
     *
     * @mbg.generated
     */
    int insert(TCpyPermanentInvestment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_permanent_investment
     *
     * @mbg.generated
     */
    int insertSelective(TCpyPermanentInvestment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_permanent_investment
     *
     * @mbg.generated
     */
    TCpyPermanentInvestment selectOneByExample(TCpyPermanentInvestmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_permanent_investment
     *
     * @mbg.generated
     */
    TCpyPermanentInvestment selectOneByExampleSelective(@Param("example") TCpyPermanentInvestmentExample example, @Param("selective") TCpyPermanentInvestment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_permanent_investment
     *
     * @mbg.generated
     */
    List<TCpyPermanentInvestment> selectByExampleSelective(@Param("example") TCpyPermanentInvestmentExample example, @Param("selective") TCpyPermanentInvestment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_permanent_investment
     *
     * @mbg.generated
     */
    List<TCpyPermanentInvestment> selectByExample(TCpyPermanentInvestmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_permanent_investment
     *
     * @mbg.generated
     */
    TCpyPermanentInvestment selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TCpyPermanentInvestment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_permanent_investment
     *
     * @mbg.generated
     */
    TCpyPermanentInvestment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_permanent_investment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TCpyPermanentInvestment record, @Param("example") TCpyPermanentInvestmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_permanent_investment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TCpyPermanentInvestment record, @Param("example") TCpyPermanentInvestmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_permanent_investment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCpyPermanentInvestment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_permanent_investment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCpyPermanentInvestment record);
}