package com.huizhi.supplier.db.dao;

import com.huizhi.supplier.db.annotation.MybatisUserInfo;
import com.huizhi.supplier.db.model.TCpyLawAnnouncement;
import com.huizhi.supplier.db.model.TCpyLawAnnouncementExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@MybatisUserInfo
public interface TCpyLawAnnouncementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_law_announcement
     *
     * @mbg.generated
     */
    long countByExample(TCpyLawAnnouncementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_law_announcement
     *
     * @mbg.generated
     */
    int deleteByExample(TCpyLawAnnouncementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_law_announcement
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_law_announcement
     *
     * @mbg.generated
     */
    int insert(TCpyLawAnnouncement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_law_announcement
     *
     * @mbg.generated
     */
    int insertSelective(TCpyLawAnnouncement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_law_announcement
     *
     * @mbg.generated
     */
    TCpyLawAnnouncement selectOneByExample(TCpyLawAnnouncementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_law_announcement
     *
     * @mbg.generated
     */
    TCpyLawAnnouncement selectOneByExampleSelective(@Param("example") TCpyLawAnnouncementExample example, @Param("selective") TCpyLawAnnouncement.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_law_announcement
     *
     * @mbg.generated
     */
    List<TCpyLawAnnouncement> selectByExampleSelective(@Param("example") TCpyLawAnnouncementExample example, @Param("selective") TCpyLawAnnouncement.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_law_announcement
     *
     * @mbg.generated
     */
    List<TCpyLawAnnouncement> selectByExample(TCpyLawAnnouncementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_law_announcement
     *
     * @mbg.generated
     */
    TCpyLawAnnouncement selectByPrimaryKeySelective(@Param("id") String id, @Param("selective") TCpyLawAnnouncement.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_law_announcement
     *
     * @mbg.generated
     */
    TCpyLawAnnouncement selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_law_announcement
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TCpyLawAnnouncement record, @Param("example") TCpyLawAnnouncementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_law_announcement
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TCpyLawAnnouncement record, @Param("example") TCpyLawAnnouncementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_law_announcement
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCpyLawAnnouncement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_law_announcement
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCpyLawAnnouncement record);
}