package com.huizhi.supplier.db.dao;

import com.huizhi.supplier.db.annotation.MybatisUserInfo;
import com.huizhi.supplier.db.model.TCpyOtherDebt;
import com.huizhi.supplier.db.model.TCpyOtherDebtExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@MybatisUserInfo
public interface TCpyOtherDebtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_other_debt
     *
     * @mbg.generated
     */
    long countByExample(TCpyOtherDebtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_other_debt
     *
     * @mbg.generated
     */
    int deleteByExample(TCpyOtherDebtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_other_debt
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_other_debt
     *
     * @mbg.generated
     */
    int insert(TCpyOtherDebt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_other_debt
     *
     * @mbg.generated
     */
    int insertSelective(TCpyOtherDebt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_other_debt
     *
     * @mbg.generated
     */
    TCpyOtherDebt selectOneByExample(TCpyOtherDebtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_other_debt
     *
     * @mbg.generated
     */
    TCpyOtherDebt selectOneByExampleSelective(@Param("example") TCpyOtherDebtExample example, @Param("selective") TCpyOtherDebt.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_other_debt
     *
     * @mbg.generated
     */
    List<TCpyOtherDebt> selectByExampleSelective(@Param("example") TCpyOtherDebtExample example, @Param("selective") TCpyOtherDebt.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_other_debt
     *
     * @mbg.generated
     */
    List<TCpyOtherDebt> selectByExample(TCpyOtherDebtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_other_debt
     *
     * @mbg.generated
     */
    TCpyOtherDebt selectByPrimaryKeySelective(@Param("id") String id, @Param("selective") TCpyOtherDebt.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_other_debt
     *
     * @mbg.generated
     */
    TCpyOtherDebt selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_other_debt
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TCpyOtherDebt record, @Param("example") TCpyOtherDebtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_other_debt
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TCpyOtherDebt record, @Param("example") TCpyOtherDebtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_other_debt
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCpyOtherDebt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_other_debt
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCpyOtherDebt record);
}