package com.huizhi.supplier.db.dao;

import com.huizhi.supplier.db.annotation.MybatisUserInfo;
import com.huizhi.supplier.db.model.TCpyForeignInvest;
import com.huizhi.supplier.db.model.TCpyForeignInvestExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@MybatisUserInfo
public interface TCpyForeignInvestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_foreign_invest
     *
     * @mbg.generated
     */
    long countByExample(TCpyForeignInvestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_foreign_invest
     *
     * @mbg.generated
     */
    int deleteByExample(TCpyForeignInvestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_foreign_invest
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_foreign_invest
     *
     * @mbg.generated
     */
    int insert(TCpyForeignInvest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_foreign_invest
     *
     * @mbg.generated
     */
    int insertSelective(TCpyForeignInvest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_foreign_invest
     *
     * @mbg.generated
     */
    TCpyForeignInvest selectOneByExample(TCpyForeignInvestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_foreign_invest
     *
     * @mbg.generated
     */
    TCpyForeignInvest selectOneByExampleSelective(@Param("example") TCpyForeignInvestExample example, @Param("selective") TCpyForeignInvest.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_foreign_invest
     *
     * @mbg.generated
     */
    List<TCpyForeignInvest> selectByExampleSelective(@Param("example") TCpyForeignInvestExample example, @Param("selective") TCpyForeignInvest.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_foreign_invest
     *
     * @mbg.generated
     */
    List<TCpyForeignInvest> selectByExample(TCpyForeignInvestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_foreign_invest
     *
     * @mbg.generated
     */
    TCpyForeignInvest selectByPrimaryKeySelective(@Param("id") String id, @Param("selective") TCpyForeignInvest.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_foreign_invest
     *
     * @mbg.generated
     */
    TCpyForeignInvest selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_foreign_invest
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TCpyForeignInvest record, @Param("example") TCpyForeignInvestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_foreign_invest
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TCpyForeignInvest record, @Param("example") TCpyForeignInvestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_foreign_invest
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCpyForeignInvest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_foreign_invest
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCpyForeignInvest record);
}