package com.huizhi.supplier.db.dao;

import com.huizhi.supplier.db.model.TCpyIndustryBreakFaithRecord;
import com.huizhi.supplier.db.model.TCpyIndustryBreakFaithRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TCpyIndustryBreakFaithRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_industry_break_faith_record
     *
     * @mbg.generated
     */
    long countByExample(TCpyIndustryBreakFaithRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_industry_break_faith_record
     *
     * @mbg.generated
     */
    int deleteByExample(TCpyIndustryBreakFaithRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_industry_break_faith_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_industry_break_faith_record
     *
     * @mbg.generated
     */
    int insert(TCpyIndustryBreakFaithRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_industry_break_faith_record
     *
     * @mbg.generated
     */
    int insertSelective(TCpyIndustryBreakFaithRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_industry_break_faith_record
     *
     * @mbg.generated
     */
    TCpyIndustryBreakFaithRecord selectOneByExample(TCpyIndustryBreakFaithRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_industry_break_faith_record
     *
     * @mbg.generated
     */
    TCpyIndustryBreakFaithRecord selectOneByExampleSelective(@Param("example") TCpyIndustryBreakFaithRecordExample example, @Param("selective") TCpyIndustryBreakFaithRecord.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_industry_break_faith_record
     *
     * @mbg.generated
     */
    List<TCpyIndustryBreakFaithRecord> selectByExampleSelective(@Param("example") TCpyIndustryBreakFaithRecordExample example, @Param("selective") TCpyIndustryBreakFaithRecord.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_industry_break_faith_record
     *
     * @mbg.generated
     */
    List<TCpyIndustryBreakFaithRecord> selectByExample(TCpyIndustryBreakFaithRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_industry_break_faith_record
     *
     * @mbg.generated
     */
    TCpyIndustryBreakFaithRecord selectByPrimaryKeySelective(@Param("id") String id, @Param("selective") TCpyIndustryBreakFaithRecord.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_industry_break_faith_record
     *
     * @mbg.generated
     */
    TCpyIndustryBreakFaithRecord selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_industry_break_faith_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TCpyIndustryBreakFaithRecord record, @Param("example") TCpyIndustryBreakFaithRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_industry_break_faith_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TCpyIndustryBreakFaithRecord record, @Param("example") TCpyIndustryBreakFaithRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_industry_break_faith_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCpyIndustryBreakFaithRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_industry_break_faith_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCpyIndustryBreakFaithRecord record);
}