package com.huizhi.supplier.db.dao;

import com.huizhi.supplier.db.model.TCpyFlangingRegulationReport;
import com.huizhi.supplier.db.model.TCpyFlangingRegulationReportExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TCpyFlangingRegulationReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_flanging_regulation_report
     *
     * @mbg.generated
     */
    long countByExample(TCpyFlangingRegulationReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_flanging_regulation_report
     *
     * @mbg.generated
     */
    int deleteByExample(TCpyFlangingRegulationReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_flanging_regulation_report
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_flanging_regulation_report
     *
     * @mbg.generated
     */
    int insert(TCpyFlangingRegulationReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_flanging_regulation_report
     *
     * @mbg.generated
     */
    int insertSelective(TCpyFlangingRegulationReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_flanging_regulation_report
     *
     * @mbg.generated
     */
    TCpyFlangingRegulationReport selectOneByExample(TCpyFlangingRegulationReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_flanging_regulation_report
     *
     * @mbg.generated
     */
    TCpyFlangingRegulationReport selectOneByExampleSelective(@Param("example") TCpyFlangingRegulationReportExample example, @Param("selective") TCpyFlangingRegulationReport.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_flanging_regulation_report
     *
     * @mbg.generated
     */
    List<TCpyFlangingRegulationReport> selectByExampleSelective(@Param("example") TCpyFlangingRegulationReportExample example, @Param("selective") TCpyFlangingRegulationReport.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_flanging_regulation_report
     *
     * @mbg.generated
     */
    List<TCpyFlangingRegulationReport> selectByExample(TCpyFlangingRegulationReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_flanging_regulation_report
     *
     * @mbg.generated
     */
    TCpyFlangingRegulationReport selectByPrimaryKeySelective(@Param("id") String id, @Param("selective") TCpyFlangingRegulationReport.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_flanging_regulation_report
     *
     * @mbg.generated
     */
    TCpyFlangingRegulationReport selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_flanging_regulation_report
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TCpyFlangingRegulationReport record, @Param("example") TCpyFlangingRegulationReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_flanging_regulation_report
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TCpyFlangingRegulationReport record, @Param("example") TCpyFlangingRegulationReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_flanging_regulation_report
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCpyFlangingRegulationReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_flanging_regulation_report
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCpyFlangingRegulationReport record);
}