package com.huizhi.supplier.db.dao;

import com.huizhi.supplier.db.annotation.MybatisUserInfo;
import com.huizhi.supplier.db.model.TCpyShareholdersConstitute;
import com.huizhi.supplier.db.model.TCpyShareholdersConstituteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@MybatisUserInfo
public interface TCpyShareholdersConstituteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_shareholders_constitute
     *
     * @mbg.generated
     */
    long countByExample(TCpyShareholdersConstituteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_shareholders_constitute
     *
     * @mbg.generated
     */
    int deleteByExample(TCpyShareholdersConstituteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_shareholders_constitute
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_shareholders_constitute
     *
     * @mbg.generated
     */
    int insert(TCpyShareholdersConstitute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_shareholders_constitute
     *
     * @mbg.generated
     */
    int insertSelective(TCpyShareholdersConstitute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_shareholders_constitute
     *
     * @mbg.generated
     */
    TCpyShareholdersConstitute selectOneByExample(TCpyShareholdersConstituteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_shareholders_constitute
     *
     * @mbg.generated
     */
    TCpyShareholdersConstitute selectOneByExampleSelective(@Param("example") TCpyShareholdersConstituteExample example, @Param("selective") TCpyShareholdersConstitute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_shareholders_constitute
     *
     * @mbg.generated
     */
    List<TCpyShareholdersConstitute> selectByExampleSelective(@Param("example") TCpyShareholdersConstituteExample example, @Param("selective") TCpyShareholdersConstitute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_shareholders_constitute
     *
     * @mbg.generated
     */
    List<TCpyShareholdersConstitute> selectByExample(TCpyShareholdersConstituteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_shareholders_constitute
     *
     * @mbg.generated
     */
    TCpyShareholdersConstitute selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TCpyShareholdersConstitute.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_shareholders_constitute
     *
     * @mbg.generated
     */
    TCpyShareholdersConstitute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_shareholders_constitute
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TCpyShareholdersConstitute record, @Param("example") TCpyShareholdersConstituteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_shareholders_constitute
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TCpyShareholdersConstitute record, @Param("example") TCpyShareholdersConstituteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_shareholders_constitute
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCpyShareholdersConstitute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_shareholders_constitute
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCpyShareholdersConstitute record);
}