package com.huizhi.supplier.db.dao;

import com.huizhi.supplier.db.annotation.MybatisUserInfo;
import com.huizhi.supplier.db.model.TCpyContractPerformance;
import com.huizhi.supplier.db.model.TCpyContractPerformanceExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@MybatisUserInfo
public interface TCpyContractPerformanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_contract_performance
     *
     * @mbg.generated
     */
    long countByExample(TCpyContractPerformanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_contract_performance
     *
     * @mbg.generated
     */
    int deleteByExample(TCpyContractPerformanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_contract_performance
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_contract_performance
     *
     * @mbg.generated
     */
    int insert(TCpyContractPerformance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_contract_performance
     *
     * @mbg.generated
     */
    int insertSelective(TCpyContractPerformance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_contract_performance
     *
     * @mbg.generated
     */
    TCpyContractPerformance selectOneByExample(TCpyContractPerformanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_contract_performance
     *
     * @mbg.generated
     */
    TCpyContractPerformance selectOneByExampleSelective(@Param("example") TCpyContractPerformanceExample example, @Param("selective") TCpyContractPerformance.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_contract_performance
     *
     * @mbg.generated
     */
    List<TCpyContractPerformance> selectByExampleSelective(@Param("example") TCpyContractPerformanceExample example, @Param("selective") TCpyContractPerformance.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_contract_performance
     *
     * @mbg.generated
     */
    List<TCpyContractPerformance> selectByExample(TCpyContractPerformanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_contract_performance
     *
     * @mbg.generated
     */
    TCpyContractPerformance selectByPrimaryKeySelective(@Param("id") String id, @Param("selective") TCpyContractPerformance.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_contract_performance
     *
     * @mbg.generated
     */
    TCpyContractPerformance selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_contract_performance
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TCpyContractPerformance record, @Param("example") TCpyContractPerformanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_contract_performance
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TCpyContractPerformance record, @Param("example") TCpyContractPerformanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_contract_performance
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCpyContractPerformance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_contract_performance
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCpyContractPerformance record);
}