package com.huizhi.supplier.db.dao;

import com.huizhi.supplier.db.model.TCpySecurities;
import com.huizhi.supplier.db.model.TCpySecuritiesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TCpySecuritiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_securities
     *
     * @mbg.generated
     */
    long countByExample(TCpySecuritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_securities
     *
     * @mbg.generated
     */
    int deleteByExample(TCpySecuritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_securities
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_securities
     *
     * @mbg.generated
     */
    int insert(TCpySecurities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_securities
     *
     * @mbg.generated
     */
    int insertSelective(TCpySecurities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_securities
     *
     * @mbg.generated
     */
    TCpySecurities selectOneByExample(TCpySecuritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_securities
     *
     * @mbg.generated
     */
    TCpySecurities selectOneByExampleSelective(@Param("example") TCpySecuritiesExample example, @Param("selective") TCpySecurities.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_securities
     *
     * @mbg.generated
     */
    List<TCpySecurities> selectByExampleSelective(@Param("example") TCpySecuritiesExample example, @Param("selective") TCpySecurities.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_securities
     *
     * @mbg.generated
     */
    List<TCpySecurities> selectByExample(TCpySecuritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_securities
     *
     * @mbg.generated
     */
    TCpySecurities selectByPrimaryKeySelective(@Param("id") String id, @Param("selective") TCpySecurities.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_securities
     *
     * @mbg.generated
     */
    TCpySecurities selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_securities
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TCpySecurities record, @Param("example") TCpySecuritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_securities
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TCpySecurities record, @Param("example") TCpySecuritiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_securities
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCpySecurities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_securities
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCpySecurities record);
}