package com.huizhi.supplier.db.dao;

import com.huizhi.supplier.db.annotation.MybatisUserInfo;
import com.huizhi.supplier.db.model.TCpyEnterpriseInfoChangeWarning;
import com.huizhi.supplier.db.model.TCpyEnterpriseInfoChangeWarningExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@MybatisUserInfo
public interface TCpyEnterpriseInfoChangeWarningMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_enterprise_info_change_warning
     *
     * @mbg.generated
     */
    long countByExample(TCpyEnterpriseInfoChangeWarningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_enterprise_info_change_warning
     *
     * @mbg.generated
     */
    int deleteByExample(TCpyEnterpriseInfoChangeWarningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_enterprise_info_change_warning
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_enterprise_info_change_warning
     *
     * @mbg.generated
     */
    int insert(TCpyEnterpriseInfoChangeWarning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_enterprise_info_change_warning
     *
     * @mbg.generated
     */
    int insertSelective(TCpyEnterpriseInfoChangeWarning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_enterprise_info_change_warning
     *
     * @mbg.generated
     */
    TCpyEnterpriseInfoChangeWarning selectOneByExample(TCpyEnterpriseInfoChangeWarningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_enterprise_info_change_warning
     *
     * @mbg.generated
     */
    TCpyEnterpriseInfoChangeWarning selectOneByExampleSelective(@Param("example") TCpyEnterpriseInfoChangeWarningExample example, @Param("selective") TCpyEnterpriseInfoChangeWarning.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_enterprise_info_change_warning
     *
     * @mbg.generated
     */
    List<TCpyEnterpriseInfoChangeWarning> selectByExampleSelective(@Param("example") TCpyEnterpriseInfoChangeWarningExample example, @Param("selective") TCpyEnterpriseInfoChangeWarning.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_enterprise_info_change_warning
     *
     * @mbg.generated
     */
    List<TCpyEnterpriseInfoChangeWarning> selectByExample(TCpyEnterpriseInfoChangeWarningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_enterprise_info_change_warning
     *
     * @mbg.generated
     */
    TCpyEnterpriseInfoChangeWarning selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TCpyEnterpriseInfoChangeWarning.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_enterprise_info_change_warning
     *
     * @mbg.generated
     */
    TCpyEnterpriseInfoChangeWarning selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_enterprise_info_change_warning
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TCpyEnterpriseInfoChangeWarning record, @Param("example") TCpyEnterpriseInfoChangeWarningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_enterprise_info_change_warning
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TCpyEnterpriseInfoChangeWarning record, @Param("example") TCpyEnterpriseInfoChangeWarningExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_enterprise_info_change_warning
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCpyEnterpriseInfoChangeWarning record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_enterprise_info_change_warning
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCpyEnterpriseInfoChangeWarning record);
}