package com.huizhi.supplier.db.dao;

import com.huizhi.supplier.db.model.TCpyCashFlow;
import com.huizhi.supplier.db.model.TCpyCashFlowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TCpyCashFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_cash_flow
     *
     * @mbg.generated
     */
    long countByExample(TCpyCashFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_cash_flow
     *
     * @mbg.generated
     */
    int deleteByExample(TCpyCashFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_cash_flow
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_cash_flow
     *
     * @mbg.generated
     */
    int insert(TCpyCashFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_cash_flow
     *
     * @mbg.generated
     */
    int insertSelective(TCpyCashFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_cash_flow
     *
     * @mbg.generated
     */
    TCpyCashFlow selectOneByExample(TCpyCashFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_cash_flow
     *
     * @mbg.generated
     */
    TCpyCashFlow selectOneByExampleSelective(@Param("example") TCpyCashFlowExample example, @Param("selective") TCpyCashFlow.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_cash_flow
     *
     * @mbg.generated
     */
    List<TCpyCashFlow> selectByExampleSelective(@Param("example") TCpyCashFlowExample example, @Param("selective") TCpyCashFlow.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_cash_flow
     *
     * @mbg.generated
     */
    List<TCpyCashFlow> selectByExample(TCpyCashFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_cash_flow
     *
     * @mbg.generated
     */
    TCpyCashFlow selectByPrimaryKeySelective(@Param("id") String id, @Param("selective") TCpyCashFlow.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_cash_flow
     *
     * @mbg.generated
     */
    TCpyCashFlow selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_cash_flow
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TCpyCashFlow record, @Param("example") TCpyCashFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_cash_flow
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TCpyCashFlow record, @Param("example") TCpyCashFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_cash_flow
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCpyCashFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_cash_flow
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCpyCashFlow record);

    List<TCpyCashFlow> selectByCompanyId(@Param("companyId") String companyId);


    TCpyCashFlow selectByCompanyIdAndYear(@Param("companyId") String companyId, @Param("year") String year);

    int updateByCompanyIdAndYear(TCpyCashFlow cashFlow);
}