package com.huizhi.supplier.db.dao;

import com.huizhi.supplier.db.model.TCpyEstateFinancing;
import com.huizhi.supplier.db.model.TCpyEstateFinancingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TCpyEstateFinancingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_estate_financing
     *
     * @mbg.generated
     */
    long countByExample(TCpyEstateFinancingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_estate_financing
     *
     * @mbg.generated
     */
    int deleteByExample(TCpyEstateFinancingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_estate_financing
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_estate_financing
     *
     * @mbg.generated
     */
    int insert(TCpyEstateFinancing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_estate_financing
     *
     * @mbg.generated
     */
    int insertSelective(TCpyEstateFinancing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_estate_financing
     *
     * @mbg.generated
     */
    TCpyEstateFinancing selectOneByExample(TCpyEstateFinancingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_estate_financing
     *
     * @mbg.generated
     */
    TCpyEstateFinancing selectOneByExampleSelective(@Param("example") TCpyEstateFinancingExample example, @Param("selective") TCpyEstateFinancing.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_estate_financing
     *
     * @mbg.generated
     */
    List<TCpyEstateFinancing> selectByExampleSelective(@Param("example") TCpyEstateFinancingExample example, @Param("selective") TCpyEstateFinancing.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_estate_financing
     *
     * @mbg.generated
     */
    List<TCpyEstateFinancing> selectByExample(TCpyEstateFinancingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_estate_financing
     *
     * @mbg.generated
     */
    TCpyEstateFinancing selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TCpyEstateFinancing.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_estate_financing
     *
     * @mbg.generated
     */
    TCpyEstateFinancing selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_estate_financing
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TCpyEstateFinancing record, @Param("example") TCpyEstateFinancingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_estate_financing
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TCpyEstateFinancing record, @Param("example") TCpyEstateFinancingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_estate_financing
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCpyEstateFinancing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_estate_financing
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCpyEstateFinancing record);
}