package com.huizhi.supplier.db.dao;

import com.huizhi.supplier.db.annotation.MybatisUserInfo;
import com.huizhi.supplier.db.model.TCpyFinancialStatement;
import com.huizhi.supplier.db.model.TCpyFinancialStatementExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@MybatisUserInfo
public interface TCpyFinancialStatementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_financial_statement
     *
     * @mbg.generated
     */
    long countByExample(TCpyFinancialStatementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_financial_statement
     *
     * @mbg.generated
     */
    int deleteByExample(TCpyFinancialStatementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_financial_statement
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_financial_statement
     *
     * @mbg.generated
     */
    int insert(TCpyFinancialStatement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_financial_statement
     *
     * @mbg.generated
     */
    int insertSelective(TCpyFinancialStatement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_financial_statement
     *
     * @mbg.generated
     */
    TCpyFinancialStatement selectOneByExample(TCpyFinancialStatementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_financial_statement
     *
     * @mbg.generated
     */
    TCpyFinancialStatement selectOneByExampleSelective(@Param("example") TCpyFinancialStatementExample example, @Param("selective") TCpyFinancialStatement.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_financial_statement
     *
     * @mbg.generated
     */
    List<TCpyFinancialStatement> selectByExampleSelective(@Param("example") TCpyFinancialStatementExample example, @Param("selective") TCpyFinancialStatement.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_financial_statement
     *
     * @mbg.generated
     */
    List<TCpyFinancialStatement> selectByExample(TCpyFinancialStatementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_financial_statement
     *
     * @mbg.generated
     */
    TCpyFinancialStatement selectByPrimaryKeySelective(@Param("id") String id, @Param("selective") TCpyFinancialStatement.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_financial_statement
     *
     * @mbg.generated
     */
    TCpyFinancialStatement selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_financial_statement
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TCpyFinancialStatement record, @Param("example") TCpyFinancialStatementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_financial_statement
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TCpyFinancialStatement record, @Param("example") TCpyFinancialStatementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_financial_statement
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCpyFinancialStatement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_financial_statement
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCpyFinancialStatement record);
}