package com.huizhi.supplier.db.dao;

import com.huizhi.supplier.db.model.TCpyDiscreditExecutor;
import com.huizhi.supplier.db.model.TCpyDiscreditExecutorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TCpyDiscreditExecutorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_discredit_executor
     *
     * @mbg.generated
     */
    long countByExample(TCpyDiscreditExecutorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_discredit_executor
     *
     * @mbg.generated
     */
    int deleteByExample(TCpyDiscreditExecutorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_discredit_executor
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_discredit_executor
     *
     * @mbg.generated
     */
    int insert(TCpyDiscreditExecutor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_discredit_executor
     *
     * @mbg.generated
     */
    int insertSelective(TCpyDiscreditExecutor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_discredit_executor
     *
     * @mbg.generated
     */
    TCpyDiscreditExecutor selectOneByExample(TCpyDiscreditExecutorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_discredit_executor
     *
     * @mbg.generated
     */
    TCpyDiscreditExecutor selectOneByExampleSelective(@Param("example") TCpyDiscreditExecutorExample example, @Param("selective") TCpyDiscreditExecutor.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_discredit_executor
     *
     * @mbg.generated
     */
    List<TCpyDiscreditExecutor> selectByExampleSelective(@Param("example") TCpyDiscreditExecutorExample example, @Param("selective") TCpyDiscreditExecutor.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_discredit_executor
     *
     * @mbg.generated
     */
    List<TCpyDiscreditExecutor> selectByExample(TCpyDiscreditExecutorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_discredit_executor
     *
     * @mbg.generated
     */
    TCpyDiscreditExecutor selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TCpyDiscreditExecutor.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_discredit_executor
     *
     * @mbg.generated
     */
    TCpyDiscreditExecutor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_discredit_executor
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TCpyDiscreditExecutor record, @Param("example") TCpyDiscreditExecutorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_discredit_executor
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TCpyDiscreditExecutor record, @Param("example") TCpyDiscreditExecutorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_discredit_executor
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCpyDiscreditExecutor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_discredit_executor
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCpyDiscreditExecutor record);
}