package com.huizhi.supplier.db.dao;

import com.huizhi.supplier.db.model.TCpyRegulationTree;
import com.huizhi.supplier.db.model.TCpyRegulationTreeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TCpyRegulationTreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_regulation_tree
     *
     * @mbg.generated
     */
    long countByExample(TCpyRegulationTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_regulation_tree
     *
     * @mbg.generated
     */
    int deleteByExample(TCpyRegulationTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_regulation_tree
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_regulation_tree
     *
     * @mbg.generated
     */
    int insert(TCpyRegulationTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_regulation_tree
     *
     * @mbg.generated
     */
    int insertSelective(TCpyRegulationTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_regulation_tree
     *
     * @mbg.generated
     */
    TCpyRegulationTree selectOneByExample(TCpyRegulationTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_regulation_tree
     *
     * @mbg.generated
     */
    TCpyRegulationTree selectOneByExampleSelective(@Param("example") TCpyRegulationTreeExample example, @Param("selective") TCpyRegulationTree.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_regulation_tree
     *
     * @mbg.generated
     */
    List<TCpyRegulationTree> selectByExampleSelective(@Param("example") TCpyRegulationTreeExample example, @Param("selective") TCpyRegulationTree.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_regulation_tree
     *
     * @mbg.generated
     */
    List<TCpyRegulationTree> selectByExample(TCpyRegulationTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_regulation_tree
     *
     * @mbg.generated
     */
    TCpyRegulationTree selectByPrimaryKeySelective(@Param("id") String id, @Param("selective") TCpyRegulationTree.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_regulation_tree
     *
     * @mbg.generated
     */
    TCpyRegulationTree selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_regulation_tree
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TCpyRegulationTree record, @Param("example") TCpyRegulationTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_regulation_tree
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TCpyRegulationTree record, @Param("example") TCpyRegulationTreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_regulation_tree
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCpyRegulationTree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_regulation_tree
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCpyRegulationTree record);
}