package com.huizhi.supplier.db.dao;

import com.huizhi.supplier.db.annotation.MybatisUserInfo;
import com.huizhi.supplier.db.model.TCpyEmployeesStatistics;
import com.huizhi.supplier.db.model.TCpyEmployeesStatisticsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@MybatisUserInfo
public interface TCpyEmployeesStatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_employees_statistics
     *
     * @mbg.generated
     */
    long countByExample(TCpyEmployeesStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_employees_statistics
     *
     * @mbg.generated
     */
    int deleteByExample(TCpyEmployeesStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_employees_statistics
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_employees_statistics
     *
     * @mbg.generated
     */
    int insert(TCpyEmployeesStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_employees_statistics
     *
     * @mbg.generated
     */
    int insertSelective(TCpyEmployeesStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_employees_statistics
     *
     * @mbg.generated
     */
    TCpyEmployeesStatistics selectOneByExample(TCpyEmployeesStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_employees_statistics
     *
     * @mbg.generated
     */
    TCpyEmployeesStatistics selectOneByExampleSelective(@Param("example") TCpyEmployeesStatisticsExample example, @Param("selective") TCpyEmployeesStatistics.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_employees_statistics
     *
     * @mbg.generated
     */
    List<TCpyEmployeesStatistics> selectByExampleSelective(@Param("example") TCpyEmployeesStatisticsExample example, @Param("selective") TCpyEmployeesStatistics.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_employees_statistics
     *
     * @mbg.generated
     */
    List<TCpyEmployeesStatistics> selectByExample(TCpyEmployeesStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_employees_statistics
     *
     * @mbg.generated
     */
    TCpyEmployeesStatistics selectByPrimaryKeySelective(@Param("id") String id, @Param("selective") TCpyEmployeesStatistics.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_employees_statistics
     *
     * @mbg.generated
     */
    TCpyEmployeesStatistics selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_employees_statistics
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TCpyEmployeesStatistics record, @Param("example") TCpyEmployeesStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_employees_statistics
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TCpyEmployeesStatistics record, @Param("example") TCpyEmployeesStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_employees_statistics
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCpyEmployeesStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_employees_statistics
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCpyEmployeesStatistics record);
}