package com.huizhi.supplier.db.dao;

import com.huizhi.supplier.db.model.TCpyAfterSaleManagement;
import com.huizhi.supplier.db.model.TCpyAfterSaleManagementExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TCpyAfterSaleManagementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_after_sale_management
     *
     * @mbg.generated
     */
    long countByExample(TCpyAfterSaleManagementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_after_sale_management
     *
     * @mbg.generated
     */
    int deleteByExample(TCpyAfterSaleManagementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_after_sale_management
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_after_sale_management
     *
     * @mbg.generated
     */
    int insert(TCpyAfterSaleManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_after_sale_management
     *
     * @mbg.generated
     */
    int insertSelective(TCpyAfterSaleManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_after_sale_management
     *
     * @mbg.generated
     */
    TCpyAfterSaleManagement selectOneByExample(TCpyAfterSaleManagementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_after_sale_management
     *
     * @mbg.generated
     */
    TCpyAfterSaleManagement selectOneByExampleSelective(@Param("example") TCpyAfterSaleManagementExample example, @Param("selective") TCpyAfterSaleManagement.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_after_sale_management
     *
     * @mbg.generated
     */
    List<TCpyAfterSaleManagement> selectByExampleSelective(@Param("example") TCpyAfterSaleManagementExample example, @Param("selective") TCpyAfterSaleManagement.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_after_sale_management
     *
     * @mbg.generated
     */
    List<TCpyAfterSaleManagement> selectByExample(TCpyAfterSaleManagementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_after_sale_management
     *
     * @mbg.generated
     */
    TCpyAfterSaleManagement selectByPrimaryKeySelective(@Param("id") String id, @Param("selective") TCpyAfterSaleManagement.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_after_sale_management
     *
     * @mbg.generated
     */
    TCpyAfterSaleManagement selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_after_sale_management
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TCpyAfterSaleManagement record, @Param("example") TCpyAfterSaleManagementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_after_sale_management
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TCpyAfterSaleManagement record, @Param("example") TCpyAfterSaleManagementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_after_sale_management
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCpyAfterSaleManagement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_after_sale_management
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCpyAfterSaleManagement record);
}