package com.huizhi.supplier.db.dao;

import com.huizhi.supplier.db.annotation.MybatisUserInfo;
import com.huizhi.supplier.db.model.TCpyTaxArrear;
import com.huizhi.supplier.db.model.TCpyTaxArrearExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@MybatisUserInfo
public interface TCpyTaxArrearMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_tax_arrear
     *
     * @mbg.generated
     */
    long countByExample(TCpyTaxArrearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_tax_arrear
     *
     * @mbg.generated
     */
    int deleteByExample(TCpyTaxArrearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_tax_arrear
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_tax_arrear
     *
     * @mbg.generated
     */
    int insert(TCpyTaxArrear record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_tax_arrear
     *
     * @mbg.generated
     */
    int insertSelective(TCpyTaxArrear record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_tax_arrear
     *
     * @mbg.generated
     */
    TCpyTaxArrear selectOneByExample(TCpyTaxArrearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_tax_arrear
     *
     * @mbg.generated
     */
    TCpyTaxArrear selectOneByExampleSelective(@Param("example") TCpyTaxArrearExample example, @Param("selective") TCpyTaxArrear.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_tax_arrear
     *
     * @mbg.generated
     */
    List<TCpyTaxArrear> selectByExampleSelective(@Param("example") TCpyTaxArrearExample example, @Param("selective") TCpyTaxArrear.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_tax_arrear
     *
     * @mbg.generated
     */
    List<TCpyTaxArrear> selectByExample(TCpyTaxArrearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_tax_arrear
     *
     * @mbg.generated
     */
    TCpyTaxArrear selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TCpyTaxArrear.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_tax_arrear
     *
     * @mbg.generated
     */
    TCpyTaxArrear selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_tax_arrear
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TCpyTaxArrear record, @Param("example") TCpyTaxArrearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_tax_arrear
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TCpyTaxArrear record, @Param("example") TCpyTaxArrearExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_tax_arrear
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TCpyTaxArrear record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_tax_arrear
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TCpyTaxArrear record);
}