package com.huizhi.supplier.db.dao;

import com.huizhi.supplier.db.annotation.MybatisUserInfo;
import com.huizhi.supplier.db.model.TFlowPointOperatePersonnel;
import com.huizhi.supplier.db.model.TFlowPointOperatePersonnelExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@MybatisUserInfo
public interface TFlowPointOperatePersonnelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flow_point_operate_personnel
     *
     * @mbg.generated
     */
    long countByExample(TFlowPointOperatePersonnelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flow_point_operate_personnel
     *
     * @mbg.generated
     */
    int deleteByExample(TFlowPointOperatePersonnelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flow_point_operate_personnel
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flow_point_operate_personnel
     *
     * @mbg.generated
     */
    int insert(TFlowPointOperatePersonnel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flow_point_operate_personnel
     *
     * @mbg.generated
     */
    int insertSelective(TFlowPointOperatePersonnel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flow_point_operate_personnel
     *
     * @mbg.generated
     */
    TFlowPointOperatePersonnel selectOneByExample(TFlowPointOperatePersonnelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flow_point_operate_personnel
     *
     * @mbg.generated
     */
    TFlowPointOperatePersonnel selectOneByExampleSelective(@Param("example") TFlowPointOperatePersonnelExample example, @Param("selective") TFlowPointOperatePersonnel.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flow_point_operate_personnel
     *
     * @mbg.generated
     */
    List<TFlowPointOperatePersonnel> selectByExampleSelective(@Param("example") TFlowPointOperatePersonnelExample example, @Param("selective") TFlowPointOperatePersonnel.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flow_point_operate_personnel
     *
     * @mbg.generated
     */
    List<TFlowPointOperatePersonnel> selectByExample(TFlowPointOperatePersonnelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flow_point_operate_personnel
     *
     * @mbg.generated
     */
    TFlowPointOperatePersonnel selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TFlowPointOperatePersonnel.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flow_point_operate_personnel
     *
     * @mbg.generated
     */
    TFlowPointOperatePersonnel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flow_point_operate_personnel
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TFlowPointOperatePersonnel record, @Param("example") TFlowPointOperatePersonnelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flow_point_operate_personnel
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TFlowPointOperatePersonnel record, @Param("example") TFlowPointOperatePersonnelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flow_point_operate_personnel
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TFlowPointOperatePersonnel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_flow_point_operate_personnel
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TFlowPointOperatePersonnel record);
}