package com.huizhi.supplier.db.dao;

import com.huizhi.supplier.db.model.TMgmSupplierBaseInfo;
import com.huizhi.supplier.db.model.TMgmSupplierBaseInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TMgmSupplierBaseInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mgm_supplier_base_info
     *
     * @mbg.generated
     */
    long countByExample(TMgmSupplierBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mgm_supplier_base_info
     *
     * @mbg.generated
     */
    int deleteByExample(TMgmSupplierBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mgm_supplier_base_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mgm_supplier_base_info
     *
     * @mbg.generated
     */
    int insert(TMgmSupplierBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mgm_supplier_base_info
     *
     * @mbg.generated
     */
    int insertSelective(TMgmSupplierBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mgm_supplier_base_info
     *
     * @mbg.generated
     */
    TMgmSupplierBaseInfo selectOneByExample(TMgmSupplierBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mgm_supplier_base_info
     *
     * @mbg.generated
     */
    TMgmSupplierBaseInfo selectOneByExampleSelective(@Param("example") TMgmSupplierBaseInfoExample example, @Param("selective") TMgmSupplierBaseInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mgm_supplier_base_info
     *
     * @mbg.generated
     */
    List<TMgmSupplierBaseInfo> selectByExampleSelective(@Param("example") TMgmSupplierBaseInfoExample example, @Param("selective") TMgmSupplierBaseInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mgm_supplier_base_info
     *
     * @mbg.generated
     */
    List<TMgmSupplierBaseInfo> selectByExample(TMgmSupplierBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mgm_supplier_base_info
     *
     * @mbg.generated
     */
    TMgmSupplierBaseInfo selectByPrimaryKeySelective(@Param("id") String id, @Param("selective") TMgmSupplierBaseInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mgm_supplier_base_info
     *
     * @mbg.generated
     */
    TMgmSupplierBaseInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mgm_supplier_base_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TMgmSupplierBaseInfo record, @Param("example") TMgmSupplierBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mgm_supplier_base_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TMgmSupplierBaseInfo record, @Param("example") TMgmSupplierBaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mgm_supplier_base_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TMgmSupplierBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mgm_supplier_base_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TMgmSupplierBaseInfo record);
}