package com.huizhi.supplier.db.dao;

import com.huizhi.supplier.db.model.TMgmSupplierSynthesisRating;
import com.huizhi.supplier.db.model.TMgmSupplierSynthesisRatingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TMgmSupplierSynthesisRatingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mgm_supplier_synthesis_rating
     *
     * @mbg.generated
     */
    long countByExample(TMgmSupplierSynthesisRatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mgm_supplier_synthesis_rating
     *
     * @mbg.generated
     */
    int deleteByExample(TMgmSupplierSynthesisRatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mgm_supplier_synthesis_rating
     *
     * @mbg.generated
     */
    int insert(TMgmSupplierSynthesisRating record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mgm_supplier_synthesis_rating
     *
     * @mbg.generated
     */
    int insertSelective(TMgmSupplierSynthesisRating record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mgm_supplier_synthesis_rating
     *
     * @mbg.generated
     */
    TMgmSupplierSynthesisRating selectOneByExample(TMgmSupplierSynthesisRatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mgm_supplier_synthesis_rating
     *
     * @mbg.generated
     */
    TMgmSupplierSynthesisRating selectOneByExampleSelective(@Param("example") TMgmSupplierSynthesisRatingExample example, @Param("selective") TMgmSupplierSynthesisRating.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mgm_supplier_synthesis_rating
     *
     * @mbg.generated
     */
    List<TMgmSupplierSynthesisRating> selectByExampleSelective(@Param("example") TMgmSupplierSynthesisRatingExample example, @Param("selective") TMgmSupplierSynthesisRating.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mgm_supplier_synthesis_rating
     *
     * @mbg.generated
     */
    List<TMgmSupplierSynthesisRating> selectByExample(TMgmSupplierSynthesisRatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mgm_supplier_synthesis_rating
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TMgmSupplierSynthesisRating record, @Param("example") TMgmSupplierSynthesisRatingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_mgm_supplier_synthesis_rating
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TMgmSupplierSynthesisRating record, @Param("example") TMgmSupplierSynthesisRatingExample example);
}