package com.huizhi.supplier.db.dao;

import com.huizhi.supplier.db.model.TPerSubjectDetailInfo;
import com.huizhi.supplier.db.model.TPerSubjectDetailInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TPerSubjectDetailInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_per_subject_detail_info
     *
     * @mbg.generated
     */
    long countByExample(TPerSubjectDetailInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_per_subject_detail_info
     *
     * @mbg.generated
     */
    int deleteByExample(TPerSubjectDetailInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_per_subject_detail_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_per_subject_detail_info
     *
     * @mbg.generated
     */
    int insert(TPerSubjectDetailInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_per_subject_detail_info
     *
     * @mbg.generated
     */
    int insertSelective(TPerSubjectDetailInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_per_subject_detail_info
     *
     * @mbg.generated
     */
    TPerSubjectDetailInfo selectOneByExample(TPerSubjectDetailInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_per_subject_detail_info
     *
     * @mbg.generated
     */
    TPerSubjectDetailInfo selectOneByExampleSelective(@Param("example") TPerSubjectDetailInfoExample example, @Param("selective") TPerSubjectDetailInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_per_subject_detail_info
     *
     * @mbg.generated
     */
    List<TPerSubjectDetailInfo> selectByExampleSelective(@Param("example") TPerSubjectDetailInfoExample example, @Param("selective") TPerSubjectDetailInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_per_subject_detail_info
     *
     * @mbg.generated
     */
    List<TPerSubjectDetailInfo> selectByExample(TPerSubjectDetailInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_per_subject_detail_info
     *
     * @mbg.generated
     */
    TPerSubjectDetailInfo selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TPerSubjectDetailInfo.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_per_subject_detail_info
     *
     * @mbg.generated
     */
    TPerSubjectDetailInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_per_subject_detail_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TPerSubjectDetailInfo record, @Param("example") TPerSubjectDetailInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_per_subject_detail_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TPerSubjectDetailInfo record, @Param("example") TPerSubjectDetailInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_per_subject_detail_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TPerSubjectDetailInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_per_subject_detail_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TPerSubjectDetailInfo record);
}