spring:
  application:
    name: supplier
    version: 1.0
hystrix:
  command:
    default:
      requestCache:
        enabled: false
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 2000
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 15000

db:
  mysql:
    supplier:
      username: spend
      password: Roma87tk
      host: 42.62.114.15
      database: evplat1
      port: 3306

server:
  port: 8090