package com.huizhi.supplier.db.model;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class TCpyShareholdersConstitute {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_shareholders_constitute.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_shareholders_constitute.company_id
     *
     * @mbg.generated
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_shareholders_constitute.shareholders_name
     *
     * @mbg.generated
     */
    private String shareholdersName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_shareholders_constitute.shareholders_type
     *
     * @mbg.generated
     */
    private String shareholdersType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_shareholders_constitute.certificate_type
     *
     * @mbg.generated
     */
    private String certificateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_shareholders_constitute.certificate_number
     *
     * @mbg.generated
     */
    private String certificateNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_shareholders_constitute.country
     *
     * @mbg.generated
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_shareholders_constitute.registered_amount
     *
     * @mbg.generated
     */
    private BigDecimal registeredAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_shareholders_constitute.invest_way
     *
     * @mbg.generated
     */
    private String investWay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_shareholders_constitute.shareholding_ratio
     *
     * @mbg.generated
     */
    private BigDecimal shareholdingRatio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_shareholders_constitute.subscribed_forehead
     *
     * @mbg.generated
     */
    private BigDecimal subscribedForehead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_shareholders_constitute.fund_currency_type
     *
     * @mbg.generated
     */
    private String fundCurrencyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_shareholders_constitute.fund_date
     *
     * @mbg.generated
     */
    private LocalDate fundDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_shareholders_constitute.amount_paid
     *
     * @mbg.generated
     */
    private BigDecimal amountPaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_shareholders_constitute.amount_currency_type
     *
     * @mbg.generated
     */
    private String amountCurrencyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_shareholders_constitute.amount_date
     *
     * @mbg.generated
     */
    private LocalDate amountDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_shareholders_constitute.create_person
     *
     * @mbg.generated
     */
    private String createPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_shareholders_constitute.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_shareholders_constitute.modify_person
     *
     * @mbg.generated
     */
    private String modifyPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_shareholders_constitute.modify_time
     *
     * @mbg.generated
     */
    private LocalDateTime modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_shareholders_constitute.data_resource
     *
     * @mbg.generated
     */
    private String dataResource;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_shareholders_constitute.id
     *
     * @return the value of t_cpy_shareholders_constitute.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_shareholders_constitute.id
     *
     * @param id the value for t_cpy_shareholders_constitute.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_shareholders_constitute.company_id
     *
     * @return the value of t_cpy_shareholders_constitute.company_id
     *
     * @mbg.generated
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_shareholders_constitute.company_id
     *
     * @param companyId the value for t_cpy_shareholders_constitute.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_shareholders_constitute.shareholders_name
     *
     * @return the value of t_cpy_shareholders_constitute.shareholders_name
     *
     * @mbg.generated
     */
    public String getShareholdersName() {
        return shareholdersName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_shareholders_constitute.shareholders_name
     *
     * @param shareholdersName the value for t_cpy_shareholders_constitute.shareholders_name
     *
     * @mbg.generated
     */
    public void setShareholdersName(String shareholdersName) {
        this.shareholdersName = shareholdersName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_shareholders_constitute.shareholders_type
     *
     * @return the value of t_cpy_shareholders_constitute.shareholders_type
     *
     * @mbg.generated
     */
    public String getShareholdersType() {
        return shareholdersType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_shareholders_constitute.shareholders_type
     *
     * @param shareholdersType the value for t_cpy_shareholders_constitute.shareholders_type
     *
     * @mbg.generated
     */
    public void setShareholdersType(String shareholdersType) {
        this.shareholdersType = shareholdersType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_shareholders_constitute.certificate_type
     *
     * @return the value of t_cpy_shareholders_constitute.certificate_type
     *
     * @mbg.generated
     */
    public String getCertificateType() {
        return certificateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_shareholders_constitute.certificate_type
     *
     * @param certificateType the value for t_cpy_shareholders_constitute.certificate_type
     *
     * @mbg.generated
     */
    public void setCertificateType(String certificateType) {
        this.certificateType = certificateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_shareholders_constitute.certificate_number
     *
     * @return the value of t_cpy_shareholders_constitute.certificate_number
     *
     * @mbg.generated
     */
    public String getCertificateNumber() {
        return certificateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_shareholders_constitute.certificate_number
     *
     * @param certificateNumber the value for t_cpy_shareholders_constitute.certificate_number
     *
     * @mbg.generated
     */
    public void setCertificateNumber(String certificateNumber) {
        this.certificateNumber = certificateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_shareholders_constitute.country
     *
     * @return the value of t_cpy_shareholders_constitute.country
     *
     * @mbg.generated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_shareholders_constitute.country
     *
     * @param country the value for t_cpy_shareholders_constitute.country
     *
     * @mbg.generated
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_shareholders_constitute.registered_amount
     *
     * @return the value of t_cpy_shareholders_constitute.registered_amount
     *
     * @mbg.generated
     */
    public BigDecimal getRegisteredAmount() {
        return registeredAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_shareholders_constitute.registered_amount
     *
     * @param registeredAmount the value for t_cpy_shareholders_constitute.registered_amount
     *
     * @mbg.generated
     */
    public void setRegisteredAmount(BigDecimal registeredAmount) {
        this.registeredAmount = registeredAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_shareholders_constitute.invest_way
     *
     * @return the value of t_cpy_shareholders_constitute.invest_way
     *
     * @mbg.generated
     */
    public String getInvestWay() {
        return investWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_shareholders_constitute.invest_way
     *
     * @param investWay the value for t_cpy_shareholders_constitute.invest_way
     *
     * @mbg.generated
     */
    public void setInvestWay(String investWay) {
        this.investWay = investWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_shareholders_constitute.shareholding_ratio
     *
     * @return the value of t_cpy_shareholders_constitute.shareholding_ratio
     *
     * @mbg.generated
     */
    public BigDecimal getShareholdingRatio() {
        return shareholdingRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_shareholders_constitute.shareholding_ratio
     *
     * @param shareholdingRatio the value for t_cpy_shareholders_constitute.shareholding_ratio
     *
     * @mbg.generated
     */
    public void setShareholdingRatio(BigDecimal shareholdingRatio) {
        this.shareholdingRatio = shareholdingRatio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_shareholders_constitute.subscribed_forehead
     *
     * @return the value of t_cpy_shareholders_constitute.subscribed_forehead
     *
     * @mbg.generated
     */
    public BigDecimal getSubscribedForehead() {
        return subscribedForehead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_shareholders_constitute.subscribed_forehead
     *
     * @param subscribedForehead the value for t_cpy_shareholders_constitute.subscribed_forehead
     *
     * @mbg.generated
     */
    public void setSubscribedForehead(BigDecimal subscribedForehead) {
        this.subscribedForehead = subscribedForehead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_shareholders_constitute.fund_currency_type
     *
     * @return the value of t_cpy_shareholders_constitute.fund_currency_type
     *
     * @mbg.generated
     */
    public String getFundCurrencyType() {
        return fundCurrencyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_shareholders_constitute.fund_currency_type
     *
     * @param fundCurrencyType the value for t_cpy_shareholders_constitute.fund_currency_type
     *
     * @mbg.generated
     */
    public void setFundCurrencyType(String fundCurrencyType) {
        this.fundCurrencyType = fundCurrencyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_shareholders_constitute.fund_date
     *
     * @return the value of t_cpy_shareholders_constitute.fund_date
     *
     * @mbg.generated
     */
    public LocalDate getFundDate() {
        return fundDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_shareholders_constitute.fund_date
     *
     * @param fundDate the value for t_cpy_shareholders_constitute.fund_date
     *
     * @mbg.generated
     */
    public void setFundDate(LocalDate fundDate) {
        this.fundDate = fundDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_shareholders_constitute.amount_paid
     *
     * @return the value of t_cpy_shareholders_constitute.amount_paid
     *
     * @mbg.generated
     */
    public BigDecimal getAmountPaid() {
        return amountPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_shareholders_constitute.amount_paid
     *
     * @param amountPaid the value for t_cpy_shareholders_constitute.amount_paid
     *
     * @mbg.generated
     */
    public void setAmountPaid(BigDecimal amountPaid) {
        this.amountPaid = amountPaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_shareholders_constitute.amount_currency_type
     *
     * @return the value of t_cpy_shareholders_constitute.amount_currency_type
     *
     * @mbg.generated
     */
    public String getAmountCurrencyType() {
        return amountCurrencyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_shareholders_constitute.amount_currency_type
     *
     * @param amountCurrencyType the value for t_cpy_shareholders_constitute.amount_currency_type
     *
     * @mbg.generated
     */
    public void setAmountCurrencyType(String amountCurrencyType) {
        this.amountCurrencyType = amountCurrencyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_shareholders_constitute.amount_date
     *
     * @return the value of t_cpy_shareholders_constitute.amount_date
     *
     * @mbg.generated
     */
    public LocalDate getAmountDate() {
        return amountDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_shareholders_constitute.amount_date
     *
     * @param amountDate the value for t_cpy_shareholders_constitute.amount_date
     *
     * @mbg.generated
     */
    public void setAmountDate(LocalDate amountDate) {
        this.amountDate = amountDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_shareholders_constitute.create_person
     *
     * @return the value of t_cpy_shareholders_constitute.create_person
     *
     * @mbg.generated
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_shareholders_constitute.create_person
     *
     * @param createPerson the value for t_cpy_shareholders_constitute.create_person
     *
     * @mbg.generated
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_shareholders_constitute.create_time
     *
     * @return the value of t_cpy_shareholders_constitute.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_shareholders_constitute.create_time
     *
     * @param createTime the value for t_cpy_shareholders_constitute.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_shareholders_constitute.modify_person
     *
     * @return the value of t_cpy_shareholders_constitute.modify_person
     *
     * @mbg.generated
     */
    public String getModifyPerson() {
        return modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_shareholders_constitute.modify_person
     *
     * @param modifyPerson the value for t_cpy_shareholders_constitute.modify_person
     *
     * @mbg.generated
     */
    public void setModifyPerson(String modifyPerson) {
        this.modifyPerson = modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_shareholders_constitute.modify_time
     *
     * @return the value of t_cpy_shareholders_constitute.modify_time
     *
     * @mbg.generated
     */
    public LocalDateTime getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_shareholders_constitute.modify_time
     *
     * @param modifyTime the value for t_cpy_shareholders_constitute.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_shareholders_constitute.data_resource
     *
     * @return the value of t_cpy_shareholders_constitute.data_resource
     *
     * @mbg.generated
     */
    public String getDataResource() {
        return dataResource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_shareholders_constitute.data_resource
     *
     * @param dataResource the value for t_cpy_shareholders_constitute.data_resource
     *
     * @mbg.generated
     */
    public void setDataResource(String dataResource) {
        this.dataResource = dataResource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_shareholders_constitute
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", companyId=").append(companyId);
        sb.append(", shareholdersName=").append(shareholdersName);
        sb.append(", shareholdersType=").append(shareholdersType);
        sb.append(", certificateType=").append(certificateType);
        sb.append(", certificateNumber=").append(certificateNumber);
        sb.append(", country=").append(country);
        sb.append(", registeredAmount=").append(registeredAmount);
        sb.append(", investWay=").append(investWay);
        sb.append(", shareholdingRatio=").append(shareholdingRatio);
        sb.append(", subscribedForehead=").append(subscribedForehead);
        sb.append(", fundCurrencyType=").append(fundCurrencyType);
        sb.append(", fundDate=").append(fundDate);
        sb.append(", amountPaid=").append(amountPaid);
        sb.append(", amountCurrencyType=").append(amountCurrencyType);
        sb.append(", amountDate=").append(amountDate);
        sb.append(", createPerson=").append(createPerson);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyPerson=").append(modifyPerson);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", dataResource=").append(dataResource);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_shareholders_constitute
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TCpyShareholdersConstitute other = (TCpyShareholdersConstitute) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCompanyId() == null ? other.getCompanyId() == null : this.getCompanyId().equals(other.getCompanyId()))
            && (this.getShareholdersName() == null ? other.getShareholdersName() == null : this.getShareholdersName().equals(other.getShareholdersName()))
            && (this.getShareholdersType() == null ? other.getShareholdersType() == null : this.getShareholdersType().equals(other.getShareholdersType()))
            && (this.getCertificateType() == null ? other.getCertificateType() == null : this.getCertificateType().equals(other.getCertificateType()))
            && (this.getCertificateNumber() == null ? other.getCertificateNumber() == null : this.getCertificateNumber().equals(other.getCertificateNumber()))
            && (this.getCountry() == null ? other.getCountry() == null : this.getCountry().equals(other.getCountry()))
            && (this.getRegisteredAmount() == null ? other.getRegisteredAmount() == null : this.getRegisteredAmount().equals(other.getRegisteredAmount()))
            && (this.getInvestWay() == null ? other.getInvestWay() == null : this.getInvestWay().equals(other.getInvestWay()))
            && (this.getShareholdingRatio() == null ? other.getShareholdingRatio() == null : this.getShareholdingRatio().equals(other.getShareholdingRatio()))
            && (this.getSubscribedForehead() == null ? other.getSubscribedForehead() == null : this.getSubscribedForehead().equals(other.getSubscribedForehead()))
            && (this.getFundCurrencyType() == null ? other.getFundCurrencyType() == null : this.getFundCurrencyType().equals(other.getFundCurrencyType()))
            && (this.getFundDate() == null ? other.getFundDate() == null : this.getFundDate().equals(other.getFundDate()))
            && (this.getAmountPaid() == null ? other.getAmountPaid() == null : this.getAmountPaid().equals(other.getAmountPaid()))
            && (this.getAmountCurrencyType() == null ? other.getAmountCurrencyType() == null : this.getAmountCurrencyType().equals(other.getAmountCurrencyType()))
            && (this.getAmountDate() == null ? other.getAmountDate() == null : this.getAmountDate().equals(other.getAmountDate()))
            && (this.getCreatePerson() == null ? other.getCreatePerson() == null : this.getCreatePerson().equals(other.getCreatePerson()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getModifyPerson() == null ? other.getModifyPerson() == null : this.getModifyPerson().equals(other.getModifyPerson()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
            && (this.getDataResource() == null ? other.getDataResource() == null : this.getDataResource().equals(other.getDataResource()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_shareholders_constitute
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCompanyId() == null) ? 0 : getCompanyId().hashCode());
        result = prime * result + ((getShareholdersName() == null) ? 0 : getShareholdersName().hashCode());
        result = prime * result + ((getShareholdersType() == null) ? 0 : getShareholdersType().hashCode());
        result = prime * result + ((getCertificateType() == null) ? 0 : getCertificateType().hashCode());
        result = prime * result + ((getCertificateNumber() == null) ? 0 : getCertificateNumber().hashCode());
        result = prime * result + ((getCountry() == null) ? 0 : getCountry().hashCode());
        result = prime * result + ((getRegisteredAmount() == null) ? 0 : getRegisteredAmount().hashCode());
        result = prime * result + ((getInvestWay() == null) ? 0 : getInvestWay().hashCode());
        result = prime * result + ((getShareholdingRatio() == null) ? 0 : getShareholdingRatio().hashCode());
        result = prime * result + ((getSubscribedForehead() == null) ? 0 : getSubscribedForehead().hashCode());
        result = prime * result + ((getFundCurrencyType() == null) ? 0 : getFundCurrencyType().hashCode());
        result = prime * result + ((getFundDate() == null) ? 0 : getFundDate().hashCode());
        result = prime * result + ((getAmountPaid() == null) ? 0 : getAmountPaid().hashCode());
        result = prime * result + ((getAmountCurrencyType() == null) ? 0 : getAmountCurrencyType().hashCode());
        result = prime * result + ((getAmountDate() == null) ? 0 : getAmountDate().hashCode());
        result = prime * result + ((getCreatePerson() == null) ? 0 : getCreatePerson().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getModifyPerson() == null) ? 0 : getModifyPerson().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getDataResource() == null) ? 0 : getDataResource().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table t_cpy_shareholders_constitute
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        companyId("company_id", "companyId", "VARCHAR", false),
        shareholdersName("shareholders_name", "shareholdersName", "VARCHAR", false),
        shareholdersType("shareholders_type", "shareholdersType", "VARCHAR", false),
        certificateType("certificate_type", "certificateType", "VARCHAR", false),
        certificateNumber("certificate_number", "certificateNumber", "VARCHAR", false),
        country("country", "country", "VARCHAR", false),
        registeredAmount("registered_amount", "registeredAmount", "DECIMAL", false),
        investWay("invest_way", "investWay", "VARCHAR", false),
        shareholdingRatio("shareholding_ratio", "shareholdingRatio", "DECIMAL", false),
        subscribedForehead("subscribed_forehead", "subscribedForehead", "DECIMAL", false),
        fundCurrencyType("fund_currency_type", "fundCurrencyType", "VARCHAR", false),
        fundDate("fund_date", "fundDate", "DATE", false),
        amountPaid("amount_paid", "amountPaid", "DECIMAL", false),
        amountCurrencyType("amount_currency_type", "amountCurrencyType", "VARCHAR", false),
        amountDate("amount_date", "amountDate", "DATE", false),
        createPerson("create_person", "createPerson", "VARCHAR", false),
        createTime("create_time", "createTime", "TIMESTAMP", false),
        modifyPerson("modify_person", "modifyPerson", "VARCHAR", false),
        modifyTime("modify_time", "modifyTime", "TIMESTAMP", false),
        dataResource("data_resource", "dataResource", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_cpy_shareholders_constitute
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_cpy_shareholders_constitute
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_cpy_shareholders_constitute
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_cpy_shareholders_constitute
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_cpy_shareholders_constitute
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_cpy_shareholders_constitute
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_shareholders_constitute
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_shareholders_constitute
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_shareholders_constitute
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_shareholders_constitute
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_shareholders_constitute
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_shareholders_constitute
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_shareholders_constitute
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_shareholders_constitute
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_shareholders_constitute
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_shareholders_constitute
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}