package com.huizhi.supplier.db.model;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class TCpyOtherDebt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_other_debt.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_other_debt.company_id
     *
     * @mbg.generated
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_other_debt.creditor_name
     *
     * @mbg.generated
     */
    private String creditorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_other_debt.amount_debt
     *
     * @mbg.generated
     */
    private BigDecimal amountDebt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_other_debt.amount_occurrence_date
     *
     * @mbg.generated
     */
    private LocalDate amountOccurrenceDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_other_debt.amount_should_date
     *
     * @mbg.generated
     */
    private LocalDate amountShouldDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_other_debt.amount_amount_override
     *
     * @mbg.generated
     */
    private BigDecimal amountAmountOverride;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_other_debt.amount_overdue_receivables
     *
     * @mbg.generated
     */
    private String amountOverdueReceivables;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_other_debt.amount_describe
     *
     * @mbg.generated
     */
    private String amountDescribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_other_debt.create_person
     *
     * @mbg.generated
     */
    private String createPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_other_debt.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_other_debt.modify_person
     *
     * @mbg.generated
     */
    private String modifyPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_other_debt.modify_time
     *
     * @mbg.generated
     */
    private LocalDateTime modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_other_debt.data_resource
     *
     * @mbg.generated
     */
    private String dataResource;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_other_debt.id
     *
     * @return the value of t_cpy_other_debt.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_other_debt.id
     *
     * @param id the value for t_cpy_other_debt.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_other_debt.company_id
     *
     * @return the value of t_cpy_other_debt.company_id
     *
     * @mbg.generated
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_other_debt.company_id
     *
     * @param companyId the value for t_cpy_other_debt.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_other_debt.creditor_name
     *
     * @return the value of t_cpy_other_debt.creditor_name
     *
     * @mbg.generated
     */
    public String getCreditorName() {
        return creditorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_other_debt.creditor_name
     *
     * @param creditorName the value for t_cpy_other_debt.creditor_name
     *
     * @mbg.generated
     */
    public void setCreditorName(String creditorName) {
        this.creditorName = creditorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_other_debt.amount_debt
     *
     * @return the value of t_cpy_other_debt.amount_debt
     *
     * @mbg.generated
     */
    public BigDecimal getAmountDebt() {
        return amountDebt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_other_debt.amount_debt
     *
     * @param amountDebt the value for t_cpy_other_debt.amount_debt
     *
     * @mbg.generated
     */
    public void setAmountDebt(BigDecimal amountDebt) {
        this.amountDebt = amountDebt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_other_debt.amount_occurrence_date
     *
     * @return the value of t_cpy_other_debt.amount_occurrence_date
     *
     * @mbg.generated
     */
    public LocalDate getAmountOccurrenceDate() {
        return amountOccurrenceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_other_debt.amount_occurrence_date
     *
     * @param amountOccurrenceDate the value for t_cpy_other_debt.amount_occurrence_date
     *
     * @mbg.generated
     */
    public void setAmountOccurrenceDate(LocalDate amountOccurrenceDate) {
        this.amountOccurrenceDate = amountOccurrenceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_other_debt.amount_should_date
     *
     * @return the value of t_cpy_other_debt.amount_should_date
     *
     * @mbg.generated
     */
    public LocalDate getAmountShouldDate() {
        return amountShouldDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_other_debt.amount_should_date
     *
     * @param amountShouldDate the value for t_cpy_other_debt.amount_should_date
     *
     * @mbg.generated
     */
    public void setAmountShouldDate(LocalDate amountShouldDate) {
        this.amountShouldDate = amountShouldDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_other_debt.amount_amount_override
     *
     * @return the value of t_cpy_other_debt.amount_amount_override
     *
     * @mbg.generated
     */
    public BigDecimal getAmountAmountOverride() {
        return amountAmountOverride;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_other_debt.amount_amount_override
     *
     * @param amountAmountOverride the value for t_cpy_other_debt.amount_amount_override
     *
     * @mbg.generated
     */
    public void setAmountAmountOverride(BigDecimal amountAmountOverride) {
        this.amountAmountOverride = amountAmountOverride;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_other_debt.amount_overdue_receivables
     *
     * @return the value of t_cpy_other_debt.amount_overdue_receivables
     *
     * @mbg.generated
     */
    public String getAmountOverdueReceivables() {
        return amountOverdueReceivables;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_other_debt.amount_overdue_receivables
     *
     * @param amountOverdueReceivables the value for t_cpy_other_debt.amount_overdue_receivables
     *
     * @mbg.generated
     */
    public void setAmountOverdueReceivables(String amountOverdueReceivables) {
        this.amountOverdueReceivables = amountOverdueReceivables;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_other_debt.amount_describe
     *
     * @return the value of t_cpy_other_debt.amount_describe
     *
     * @mbg.generated
     */
    public String getAmountDescribe() {
        return amountDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_other_debt.amount_describe
     *
     * @param amountDescribe the value for t_cpy_other_debt.amount_describe
     *
     * @mbg.generated
     */
    public void setAmountDescribe(String amountDescribe) {
        this.amountDescribe = amountDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_other_debt.create_person
     *
     * @return the value of t_cpy_other_debt.create_person
     *
     * @mbg.generated
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_other_debt.create_person
     *
     * @param createPerson the value for t_cpy_other_debt.create_person
     *
     * @mbg.generated
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_other_debt.create_time
     *
     * @return the value of t_cpy_other_debt.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_other_debt.create_time
     *
     * @param createTime the value for t_cpy_other_debt.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_other_debt.modify_person
     *
     * @return the value of t_cpy_other_debt.modify_person
     *
     * @mbg.generated
     */
    public String getModifyPerson() {
        return modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_other_debt.modify_person
     *
     * @param modifyPerson the value for t_cpy_other_debt.modify_person
     *
     * @mbg.generated
     */
    public void setModifyPerson(String modifyPerson) {
        this.modifyPerson = modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_other_debt.modify_time
     *
     * @return the value of t_cpy_other_debt.modify_time
     *
     * @mbg.generated
     */
    public LocalDateTime getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_other_debt.modify_time
     *
     * @param modifyTime the value for t_cpy_other_debt.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_other_debt.data_resource
     *
     * @return the value of t_cpy_other_debt.data_resource
     *
     * @mbg.generated
     */
    public String getDataResource() {
        return dataResource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_other_debt.data_resource
     *
     * @param dataResource the value for t_cpy_other_debt.data_resource
     *
     * @mbg.generated
     */
    public void setDataResource(String dataResource) {
        this.dataResource = dataResource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_other_debt
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", companyId=").append(companyId);
        sb.append(", creditorName=").append(creditorName);
        sb.append(", amountDebt=").append(amountDebt);
        sb.append(", amountOccurrenceDate=").append(amountOccurrenceDate);
        sb.append(", amountShouldDate=").append(amountShouldDate);
        sb.append(", amountAmountOverride=").append(amountAmountOverride);
        sb.append(", amountOverdueReceivables=").append(amountOverdueReceivables);
        sb.append(", amountDescribe=").append(amountDescribe);
        sb.append(", createPerson=").append(createPerson);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyPerson=").append(modifyPerson);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", dataResource=").append(dataResource);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_other_debt
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TCpyOtherDebt other = (TCpyOtherDebt) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCompanyId() == null ? other.getCompanyId() == null : this.getCompanyId().equals(other.getCompanyId()))
            && (this.getCreditorName() == null ? other.getCreditorName() == null : this.getCreditorName().equals(other.getCreditorName()))
            && (this.getAmountDebt() == null ? other.getAmountDebt() == null : this.getAmountDebt().equals(other.getAmountDebt()))
            && (this.getAmountOccurrenceDate() == null ? other.getAmountOccurrenceDate() == null : this.getAmountOccurrenceDate().equals(other.getAmountOccurrenceDate()))
            && (this.getAmountShouldDate() == null ? other.getAmountShouldDate() == null : this.getAmountShouldDate().equals(other.getAmountShouldDate()))
            && (this.getAmountAmountOverride() == null ? other.getAmountAmountOverride() == null : this.getAmountAmountOverride().equals(other.getAmountAmountOverride()))
            && (this.getAmountOverdueReceivables() == null ? other.getAmountOverdueReceivables() == null : this.getAmountOverdueReceivables().equals(other.getAmountOverdueReceivables()))
            && (this.getAmountDescribe() == null ? other.getAmountDescribe() == null : this.getAmountDescribe().equals(other.getAmountDescribe()))
            && (this.getCreatePerson() == null ? other.getCreatePerson() == null : this.getCreatePerson().equals(other.getCreatePerson()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getModifyPerson() == null ? other.getModifyPerson() == null : this.getModifyPerson().equals(other.getModifyPerson()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
            && (this.getDataResource() == null ? other.getDataResource() == null : this.getDataResource().equals(other.getDataResource()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_other_debt
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCompanyId() == null) ? 0 : getCompanyId().hashCode());
        result = prime * result + ((getCreditorName() == null) ? 0 : getCreditorName().hashCode());
        result = prime * result + ((getAmountDebt() == null) ? 0 : getAmountDebt().hashCode());
        result = prime * result + ((getAmountOccurrenceDate() == null) ? 0 : getAmountOccurrenceDate().hashCode());
        result = prime * result + ((getAmountShouldDate() == null) ? 0 : getAmountShouldDate().hashCode());
        result = prime * result + ((getAmountAmountOverride() == null) ? 0 : getAmountAmountOverride().hashCode());
        result = prime * result + ((getAmountOverdueReceivables() == null) ? 0 : getAmountOverdueReceivables().hashCode());
        result = prime * result + ((getAmountDescribe() == null) ? 0 : getAmountDescribe().hashCode());
        result = prime * result + ((getCreatePerson() == null) ? 0 : getCreatePerson().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getModifyPerson() == null) ? 0 : getModifyPerson().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getDataResource() == null) ? 0 : getDataResource().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table t_cpy_other_debt
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        companyId("company_id", "companyId", "VARCHAR", false),
        creditorName("creditor_name", "creditorName", "VARCHAR", false),
        amountDebt("amount_debt", "amountDebt", "DECIMAL", false),
        amountOccurrenceDate("amount_occurrence_date", "amountOccurrenceDate", "DATE", false),
        amountShouldDate("amount_should_date", "amountShouldDate", "DATE", false),
        amountAmountOverride("amount_amount_override", "amountAmountOverride", "DECIMAL", false),
        amountOverdueReceivables("amount_overdue_receivables", "amountOverdueReceivables", "VARCHAR", false),
        amountDescribe("amount_describe", "amountDescribe", "VARCHAR", false),
        createPerson("create_person", "createPerson", "VARCHAR", false),
        createTime("create_time", "createTime", "TIMESTAMP", false),
        modifyPerson("modify_person", "modifyPerson", "VARCHAR", false),
        modifyTime("modify_time", "modifyTime", "TIMESTAMP", false),
        dataResource("data_resource", "dataResource", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_cpy_other_debt
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_cpy_other_debt
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_cpy_other_debt
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_cpy_other_debt
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_cpy_other_debt
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_cpy_other_debt
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_other_debt
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_other_debt
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_other_debt
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_other_debt
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_other_debt
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_other_debt
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_other_debt
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_other_debt
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_other_debt
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_other_debt
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}