package com.huizhi.supplier.db.model;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class TCpyNonBankFinancing {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_non_bank_financing.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_non_bank_financing.company_id
     *
     * @mbg.generated
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_non_bank_financing.financing_way
     *
     * @mbg.generated
     */
    private String financingWay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_non_bank_financing.financing_gist
     *
     * @mbg.generated
     */
    private String financingGist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_non_bank_financing.financing_purpose
     *
     * @mbg.generated
     */
    private String financingPurpose;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_non_bank_financing.financing_object
     *
     * @mbg.generated
     */
    private String financingObject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_non_bank_financing.financing_money
     *
     * @mbg.generated
     */
    private BigDecimal financingMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_non_bank_financing.financing_deadline
     *
     * @mbg.generated
     */
    private String financingDeadline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_non_bank_financing.financing_start_date
     *
     * @mbg.generated
     */
    private LocalDate financingStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_non_bank_financing.nonBank_financing_guarantees
     *
     * @mbg.generated
     */
    private String nonbankFinancingGuarantees;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_non_bank_financing.create_person
     *
     * @mbg.generated
     */
    private String createPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_non_bank_financing.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_non_bank_financing.modify_person
     *
     * @mbg.generated
     */
    private String modifyPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_non_bank_financing.modify_time
     *
     * @mbg.generated
     */
    private LocalDateTime modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_non_bank_financing.data_resource
     *
     * @mbg.generated
     */
    private String dataResource;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_non_bank_financing.id
     *
     * @return the value of t_cpy_non_bank_financing.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_non_bank_financing.id
     *
     * @param id the value for t_cpy_non_bank_financing.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_non_bank_financing.company_id
     *
     * @return the value of t_cpy_non_bank_financing.company_id
     *
     * @mbg.generated
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_non_bank_financing.company_id
     *
     * @param companyId the value for t_cpy_non_bank_financing.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_non_bank_financing.financing_way
     *
     * @return the value of t_cpy_non_bank_financing.financing_way
     *
     * @mbg.generated
     */
    public String getFinancingWay() {
        return financingWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_non_bank_financing.financing_way
     *
     * @param financingWay the value for t_cpy_non_bank_financing.financing_way
     *
     * @mbg.generated
     */
    public void setFinancingWay(String financingWay) {
        this.financingWay = financingWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_non_bank_financing.financing_gist
     *
     * @return the value of t_cpy_non_bank_financing.financing_gist
     *
     * @mbg.generated
     */
    public String getFinancingGist() {
        return financingGist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_non_bank_financing.financing_gist
     *
     * @param financingGist the value for t_cpy_non_bank_financing.financing_gist
     *
     * @mbg.generated
     */
    public void setFinancingGist(String financingGist) {
        this.financingGist = financingGist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_non_bank_financing.financing_purpose
     *
     * @return the value of t_cpy_non_bank_financing.financing_purpose
     *
     * @mbg.generated
     */
    public String getFinancingPurpose() {
        return financingPurpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_non_bank_financing.financing_purpose
     *
     * @param financingPurpose the value for t_cpy_non_bank_financing.financing_purpose
     *
     * @mbg.generated
     */
    public void setFinancingPurpose(String financingPurpose) {
        this.financingPurpose = financingPurpose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_non_bank_financing.financing_object
     *
     * @return the value of t_cpy_non_bank_financing.financing_object
     *
     * @mbg.generated
     */
    public String getFinancingObject() {
        return financingObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_non_bank_financing.financing_object
     *
     * @param financingObject the value for t_cpy_non_bank_financing.financing_object
     *
     * @mbg.generated
     */
    public void setFinancingObject(String financingObject) {
        this.financingObject = financingObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_non_bank_financing.financing_money
     *
     * @return the value of t_cpy_non_bank_financing.financing_money
     *
     * @mbg.generated
     */
    public BigDecimal getFinancingMoney() {
        return financingMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_non_bank_financing.financing_money
     *
     * @param financingMoney the value for t_cpy_non_bank_financing.financing_money
     *
     * @mbg.generated
     */
    public void setFinancingMoney(BigDecimal financingMoney) {
        this.financingMoney = financingMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_non_bank_financing.financing_deadline
     *
     * @return the value of t_cpy_non_bank_financing.financing_deadline
     *
     * @mbg.generated
     */
    public String getFinancingDeadline() {
        return financingDeadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_non_bank_financing.financing_deadline
     *
     * @param financingDeadline the value for t_cpy_non_bank_financing.financing_deadline
     *
     * @mbg.generated
     */
    public void setFinancingDeadline(String financingDeadline) {
        this.financingDeadline = financingDeadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_non_bank_financing.financing_start_date
     *
     * @return the value of t_cpy_non_bank_financing.financing_start_date
     *
     * @mbg.generated
     */
    public LocalDate getFinancingStartDate() {
        return financingStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_non_bank_financing.financing_start_date
     *
     * @param financingStartDate the value for t_cpy_non_bank_financing.financing_start_date
     *
     * @mbg.generated
     */
    public void setFinancingStartDate(LocalDate financingStartDate) {
        this.financingStartDate = financingStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_non_bank_financing.nonBank_financing_guarantees
     *
     * @return the value of t_cpy_non_bank_financing.nonBank_financing_guarantees
     *
     * @mbg.generated
     */
    public String getNonbankFinancingGuarantees() {
        return nonbankFinancingGuarantees;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_non_bank_financing.nonBank_financing_guarantees
     *
     * @param nonbankFinancingGuarantees the value for t_cpy_non_bank_financing.nonBank_financing_guarantees
     *
     * @mbg.generated
     */
    public void setNonbankFinancingGuarantees(String nonbankFinancingGuarantees) {
        this.nonbankFinancingGuarantees = nonbankFinancingGuarantees;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_non_bank_financing.create_person
     *
     * @return the value of t_cpy_non_bank_financing.create_person
     *
     * @mbg.generated
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_non_bank_financing.create_person
     *
     * @param createPerson the value for t_cpy_non_bank_financing.create_person
     *
     * @mbg.generated
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_non_bank_financing.create_time
     *
     * @return the value of t_cpy_non_bank_financing.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_non_bank_financing.create_time
     *
     * @param createTime the value for t_cpy_non_bank_financing.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_non_bank_financing.modify_person
     *
     * @return the value of t_cpy_non_bank_financing.modify_person
     *
     * @mbg.generated
     */
    public String getModifyPerson() {
        return modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_non_bank_financing.modify_person
     *
     * @param modifyPerson the value for t_cpy_non_bank_financing.modify_person
     *
     * @mbg.generated
     */
    public void setModifyPerson(String modifyPerson) {
        this.modifyPerson = modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_non_bank_financing.modify_time
     *
     * @return the value of t_cpy_non_bank_financing.modify_time
     *
     * @mbg.generated
     */
    public LocalDateTime getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_non_bank_financing.modify_time
     *
     * @param modifyTime the value for t_cpy_non_bank_financing.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_non_bank_financing.data_resource
     *
     * @return the value of t_cpy_non_bank_financing.data_resource
     *
     * @mbg.generated
     */
    public String getDataResource() {
        return dataResource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_non_bank_financing.data_resource
     *
     * @param dataResource the value for t_cpy_non_bank_financing.data_resource
     *
     * @mbg.generated
     */
    public void setDataResource(String dataResource) {
        this.dataResource = dataResource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_non_bank_financing
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", companyId=").append(companyId);
        sb.append(", financingWay=").append(financingWay);
        sb.append(", financingGist=").append(financingGist);
        sb.append(", financingPurpose=").append(financingPurpose);
        sb.append(", financingObject=").append(financingObject);
        sb.append(", financingMoney=").append(financingMoney);
        sb.append(", financingDeadline=").append(financingDeadline);
        sb.append(", financingStartDate=").append(financingStartDate);
        sb.append(", nonbankFinancingGuarantees=").append(nonbankFinancingGuarantees);
        sb.append(", createPerson=").append(createPerson);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyPerson=").append(modifyPerson);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", dataResource=").append(dataResource);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_non_bank_financing
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TCpyNonBankFinancing other = (TCpyNonBankFinancing) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCompanyId() == null ? other.getCompanyId() == null : this.getCompanyId().equals(other.getCompanyId()))
            && (this.getFinancingWay() == null ? other.getFinancingWay() == null : this.getFinancingWay().equals(other.getFinancingWay()))
            && (this.getFinancingGist() == null ? other.getFinancingGist() == null : this.getFinancingGist().equals(other.getFinancingGist()))
            && (this.getFinancingPurpose() == null ? other.getFinancingPurpose() == null : this.getFinancingPurpose().equals(other.getFinancingPurpose()))
            && (this.getFinancingObject() == null ? other.getFinancingObject() == null : this.getFinancingObject().equals(other.getFinancingObject()))
            && (this.getFinancingMoney() == null ? other.getFinancingMoney() == null : this.getFinancingMoney().equals(other.getFinancingMoney()))
            && (this.getFinancingDeadline() == null ? other.getFinancingDeadline() == null : this.getFinancingDeadline().equals(other.getFinancingDeadline()))
            && (this.getFinancingStartDate() == null ? other.getFinancingStartDate() == null : this.getFinancingStartDate().equals(other.getFinancingStartDate()))
            && (this.getNonbankFinancingGuarantees() == null ? other.getNonbankFinancingGuarantees() == null : this.getNonbankFinancingGuarantees().equals(other.getNonbankFinancingGuarantees()))
            && (this.getCreatePerson() == null ? other.getCreatePerson() == null : this.getCreatePerson().equals(other.getCreatePerson()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getModifyPerson() == null ? other.getModifyPerson() == null : this.getModifyPerson().equals(other.getModifyPerson()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
            && (this.getDataResource() == null ? other.getDataResource() == null : this.getDataResource().equals(other.getDataResource()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_non_bank_financing
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCompanyId() == null) ? 0 : getCompanyId().hashCode());
        result = prime * result + ((getFinancingWay() == null) ? 0 : getFinancingWay().hashCode());
        result = prime * result + ((getFinancingGist() == null) ? 0 : getFinancingGist().hashCode());
        result = prime * result + ((getFinancingPurpose() == null) ? 0 : getFinancingPurpose().hashCode());
        result = prime * result + ((getFinancingObject() == null) ? 0 : getFinancingObject().hashCode());
        result = prime * result + ((getFinancingMoney() == null) ? 0 : getFinancingMoney().hashCode());
        result = prime * result + ((getFinancingDeadline() == null) ? 0 : getFinancingDeadline().hashCode());
        result = prime * result + ((getFinancingStartDate() == null) ? 0 : getFinancingStartDate().hashCode());
        result = prime * result + ((getNonbankFinancingGuarantees() == null) ? 0 : getNonbankFinancingGuarantees().hashCode());
        result = prime * result + ((getCreatePerson() == null) ? 0 : getCreatePerson().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getModifyPerson() == null) ? 0 : getModifyPerson().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getDataResource() == null) ? 0 : getDataResource().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table t_cpy_non_bank_financing
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        companyId("company_id", "companyId", "VARCHAR", false),
        financingWay("financing_way", "financingWay", "VARCHAR", false),
        financingGist("financing_gist", "financingGist", "VARCHAR", false),
        financingPurpose("financing_purpose", "financingPurpose", "VARCHAR", false),
        financingObject("financing_object", "financingObject", "VARCHAR", false),
        financingMoney("financing_money", "financingMoney", "DECIMAL", false),
        financingDeadline("financing_deadline", "financingDeadline", "VARCHAR", false),
        financingStartDate("financing_start_date", "financingStartDate", "DATE", false),
        nonbankFinancingGuarantees("nonBank_financing_guarantees", "nonbankFinancingGuarantees", "VARCHAR", false),
        createPerson("create_person", "createPerson", "VARCHAR", false),
        createTime("create_time", "createTime", "TIMESTAMP", false),
        modifyPerson("modify_person", "modifyPerson", "VARCHAR", false),
        modifyTime("modify_time", "modifyTime", "TIMESTAMP", false),
        dataResource("data_resource", "dataResource", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_cpy_non_bank_financing
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_cpy_non_bank_financing
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_cpy_non_bank_financing
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_cpy_non_bank_financing
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_cpy_non_bank_financing
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_cpy_non_bank_financing
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_non_bank_financing
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_non_bank_financing
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_non_bank_financing
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_non_bank_financing
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_non_bank_financing
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_non_bank_financing
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_non_bank_financing
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_non_bank_financing
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_non_bank_financing
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_non_bank_financing
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}