package com.huizhi.supplier.db.model;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class TCpyLegal {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_legal.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_legal.company_id
     *
     * @mbg.generated
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_legal.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_legal.post
     *
     * @mbg.generated
     */
    private String post;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_legal.nationality
     *
     * @mbg.generated
     */
    private String nationality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_legal.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_legal.certificate_type
     *
     * @mbg.generated
     */
    private String certificateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_legal.certificate_number
     *
     * @mbg.generated
     */
    private String certificateNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_legal.academic
     *
     * @mbg.generated
     */
    private String academic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_legal.degree
     *
     * @mbg.generated
     */
    private String degree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_legal.Industry_experience
     *
     * @mbg.generated
     */
    private String industryExperience;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_legal.management_experience
     *
     * @mbg.generated
     */
    private String managementExperience;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_legal.experience
     *
     * @mbg.generated
     */
    private String experience;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_legal.qualification_name
     *
     * @mbg.generated
     */
    private String qualificationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_legal.qualification_no
     *
     * @mbg.generated
     */
    private String qualificationNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_legal.technical_name
     *
     * @mbg.generated
     */
    private String technicalName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_legal.credit_record
     *
     * @mbg.generated
     */
    private String creditRecord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_legal.start_date
     *
     * @mbg.generated
     */
    private LocalDate startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_legal.unit
     *
     * @mbg.generated
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_legal.graduate_institutions
     *
     * @mbg.generated
     */
    private String graduateInstitutions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_legal.birthday
     *
     * @mbg.generated
     */
    private LocalDate birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_legal.marriage
     *
     * @mbg.generated
     */
    private String marriage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_legal.telephone
     *
     * @mbg.generated
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_legal.postal_address
     *
     * @mbg.generated
     */
    private String postalAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_legal.permanent_address
     *
     * @mbg.generated
     */
    private String permanentAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_legal.join_time
     *
     * @mbg.generated
     */
    private LocalDate joinTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_legal.whethe_partake_operate
     *
     * @mbg.generated
     */
    private String whethePartakeOperate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_legal.personal_credit_report
     *
     * @mbg.generated
     */
    private String personalCreditReport;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_legal.resume
     *
     * @mbg.generated
     */
    private String resume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_legal.create_person
     *
     * @mbg.generated
     */
    private String createPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_legal.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_legal.modify_person
     *
     * @mbg.generated
     */
    private String modifyPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_legal.modify_time
     *
     * @mbg.generated
     */
    private LocalDateTime modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_legal.data_resource
     *
     * @mbg.generated
     */
    private String dataResource;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_legal.id
     *
     * @return the value of t_cpy_legal.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_legal.id
     *
     * @param id the value for t_cpy_legal.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_legal.company_id
     *
     * @return the value of t_cpy_legal.company_id
     *
     * @mbg.generated
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_legal.company_id
     *
     * @param companyId the value for t_cpy_legal.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_legal.name
     *
     * @return the value of t_cpy_legal.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_legal.name
     *
     * @param name the value for t_cpy_legal.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_legal.post
     *
     * @return the value of t_cpy_legal.post
     *
     * @mbg.generated
     */
    public String getPost() {
        return post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_legal.post
     *
     * @param post the value for t_cpy_legal.post
     *
     * @mbg.generated
     */
    public void setPost(String post) {
        this.post = post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_legal.nationality
     *
     * @return the value of t_cpy_legal.nationality
     *
     * @mbg.generated
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_legal.nationality
     *
     * @param nationality the value for t_cpy_legal.nationality
     *
     * @mbg.generated
     */
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_legal.sex
     *
     * @return the value of t_cpy_legal.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_legal.sex
     *
     * @param sex the value for t_cpy_legal.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_legal.certificate_type
     *
     * @return the value of t_cpy_legal.certificate_type
     *
     * @mbg.generated
     */
    public String getCertificateType() {
        return certificateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_legal.certificate_type
     *
     * @param certificateType the value for t_cpy_legal.certificate_type
     *
     * @mbg.generated
     */
    public void setCertificateType(String certificateType) {
        this.certificateType = certificateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_legal.certificate_number
     *
     * @return the value of t_cpy_legal.certificate_number
     *
     * @mbg.generated
     */
    public String getCertificateNumber() {
        return certificateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_legal.certificate_number
     *
     * @param certificateNumber the value for t_cpy_legal.certificate_number
     *
     * @mbg.generated
     */
    public void setCertificateNumber(String certificateNumber) {
        this.certificateNumber = certificateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_legal.academic
     *
     * @return the value of t_cpy_legal.academic
     *
     * @mbg.generated
     */
    public String getAcademic() {
        return academic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_legal.academic
     *
     * @param academic the value for t_cpy_legal.academic
     *
     * @mbg.generated
     */
    public void setAcademic(String academic) {
        this.academic = academic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_legal.degree
     *
     * @return the value of t_cpy_legal.degree
     *
     * @mbg.generated
     */
    public String getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_legal.degree
     *
     * @param degree the value for t_cpy_legal.degree
     *
     * @mbg.generated
     */
    public void setDegree(String degree) {
        this.degree = degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_legal.Industry_experience
     *
     * @return the value of t_cpy_legal.Industry_experience
     *
     * @mbg.generated
     */
    public String getIndustryExperience() {
        return industryExperience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_legal.Industry_experience
     *
     * @param industryExperience the value for t_cpy_legal.Industry_experience
     *
     * @mbg.generated
     */
    public void setIndustryExperience(String industryExperience) {
        this.industryExperience = industryExperience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_legal.management_experience
     *
     * @return the value of t_cpy_legal.management_experience
     *
     * @mbg.generated
     */
    public String getManagementExperience() {
        return managementExperience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_legal.management_experience
     *
     * @param managementExperience the value for t_cpy_legal.management_experience
     *
     * @mbg.generated
     */
    public void setManagementExperience(String managementExperience) {
        this.managementExperience = managementExperience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_legal.experience
     *
     * @return the value of t_cpy_legal.experience
     *
     * @mbg.generated
     */
    public String getExperience() {
        return experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_legal.experience
     *
     * @param experience the value for t_cpy_legal.experience
     *
     * @mbg.generated
     */
    public void setExperience(String experience) {
        this.experience = experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_legal.qualification_name
     *
     * @return the value of t_cpy_legal.qualification_name
     *
     * @mbg.generated
     */
    public String getQualificationName() {
        return qualificationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_legal.qualification_name
     *
     * @param qualificationName the value for t_cpy_legal.qualification_name
     *
     * @mbg.generated
     */
    public void setQualificationName(String qualificationName) {
        this.qualificationName = qualificationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_legal.qualification_no
     *
     * @return the value of t_cpy_legal.qualification_no
     *
     * @mbg.generated
     */
    public String getQualificationNo() {
        return qualificationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_legal.qualification_no
     *
     * @param qualificationNo the value for t_cpy_legal.qualification_no
     *
     * @mbg.generated
     */
    public void setQualificationNo(String qualificationNo) {
        this.qualificationNo = qualificationNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_legal.technical_name
     *
     * @return the value of t_cpy_legal.technical_name
     *
     * @mbg.generated
     */
    public String getTechnicalName() {
        return technicalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_legal.technical_name
     *
     * @param technicalName the value for t_cpy_legal.technical_name
     *
     * @mbg.generated
     */
    public void setTechnicalName(String technicalName) {
        this.technicalName = technicalName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_legal.credit_record
     *
     * @return the value of t_cpy_legal.credit_record
     *
     * @mbg.generated
     */
    public String getCreditRecord() {
        return creditRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_legal.credit_record
     *
     * @param creditRecord the value for t_cpy_legal.credit_record
     *
     * @mbg.generated
     */
    public void setCreditRecord(String creditRecord) {
        this.creditRecord = creditRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_legal.start_date
     *
     * @return the value of t_cpy_legal.start_date
     *
     * @mbg.generated
     */
    public LocalDate getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_legal.start_date
     *
     * @param startDate the value for t_cpy_legal.start_date
     *
     * @mbg.generated
     */
    public void setStartDate(LocalDate startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_legal.unit
     *
     * @return the value of t_cpy_legal.unit
     *
     * @mbg.generated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_legal.unit
     *
     * @param unit the value for t_cpy_legal.unit
     *
     * @mbg.generated
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_legal.graduate_institutions
     *
     * @return the value of t_cpy_legal.graduate_institutions
     *
     * @mbg.generated
     */
    public String getGraduateInstitutions() {
        return graduateInstitutions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_legal.graduate_institutions
     *
     * @param graduateInstitutions the value for t_cpy_legal.graduate_institutions
     *
     * @mbg.generated
     */
    public void setGraduateInstitutions(String graduateInstitutions) {
        this.graduateInstitutions = graduateInstitutions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_legal.birthday
     *
     * @return the value of t_cpy_legal.birthday
     *
     * @mbg.generated
     */
    public LocalDate getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_legal.birthday
     *
     * @param birthday the value for t_cpy_legal.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(LocalDate birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_legal.marriage
     *
     * @return the value of t_cpy_legal.marriage
     *
     * @mbg.generated
     */
    public String getMarriage() {
        return marriage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_legal.marriage
     *
     * @param marriage the value for t_cpy_legal.marriage
     *
     * @mbg.generated
     */
    public void setMarriage(String marriage) {
        this.marriage = marriage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_legal.telephone
     *
     * @return the value of t_cpy_legal.telephone
     *
     * @mbg.generated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_legal.telephone
     *
     * @param telephone the value for t_cpy_legal.telephone
     *
     * @mbg.generated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_legal.postal_address
     *
     * @return the value of t_cpy_legal.postal_address
     *
     * @mbg.generated
     */
    public String getPostalAddress() {
        return postalAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_legal.postal_address
     *
     * @param postalAddress the value for t_cpy_legal.postal_address
     *
     * @mbg.generated
     */
    public void setPostalAddress(String postalAddress) {
        this.postalAddress = postalAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_legal.permanent_address
     *
     * @return the value of t_cpy_legal.permanent_address
     *
     * @mbg.generated
     */
    public String getPermanentAddress() {
        return permanentAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_legal.permanent_address
     *
     * @param permanentAddress the value for t_cpy_legal.permanent_address
     *
     * @mbg.generated
     */
    public void setPermanentAddress(String permanentAddress) {
        this.permanentAddress = permanentAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_legal.join_time
     *
     * @return the value of t_cpy_legal.join_time
     *
     * @mbg.generated
     */
    public LocalDate getJoinTime() {
        return joinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_legal.join_time
     *
     * @param joinTime the value for t_cpy_legal.join_time
     *
     * @mbg.generated
     */
    public void setJoinTime(LocalDate joinTime) {
        this.joinTime = joinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_legal.whethe_partake_operate
     *
     * @return the value of t_cpy_legal.whethe_partake_operate
     *
     * @mbg.generated
     */
    public String getWhethePartakeOperate() {
        return whethePartakeOperate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_legal.whethe_partake_operate
     *
     * @param whethePartakeOperate the value for t_cpy_legal.whethe_partake_operate
     *
     * @mbg.generated
     */
    public void setWhethePartakeOperate(String whethePartakeOperate) {
        this.whethePartakeOperate = whethePartakeOperate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_legal.personal_credit_report
     *
     * @return the value of t_cpy_legal.personal_credit_report
     *
     * @mbg.generated
     */
    public String getPersonalCreditReport() {
        return personalCreditReport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_legal.personal_credit_report
     *
     * @param personalCreditReport the value for t_cpy_legal.personal_credit_report
     *
     * @mbg.generated
     */
    public void setPersonalCreditReport(String personalCreditReport) {
        this.personalCreditReport = personalCreditReport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_legal.resume
     *
     * @return the value of t_cpy_legal.resume
     *
     * @mbg.generated
     */
    public String getResume() {
        return resume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_legal.resume
     *
     * @param resume the value for t_cpy_legal.resume
     *
     * @mbg.generated
     */
    public void setResume(String resume) {
        this.resume = resume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_legal.create_person
     *
     * @return the value of t_cpy_legal.create_person
     *
     * @mbg.generated
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_legal.create_person
     *
     * @param createPerson the value for t_cpy_legal.create_person
     *
     * @mbg.generated
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_legal.create_time
     *
     * @return the value of t_cpy_legal.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_legal.create_time
     *
     * @param createTime the value for t_cpy_legal.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_legal.modify_person
     *
     * @return the value of t_cpy_legal.modify_person
     *
     * @mbg.generated
     */
    public String getModifyPerson() {
        return modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_legal.modify_person
     *
     * @param modifyPerson the value for t_cpy_legal.modify_person
     *
     * @mbg.generated
     */
    public void setModifyPerson(String modifyPerson) {
        this.modifyPerson = modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_legal.modify_time
     *
     * @return the value of t_cpy_legal.modify_time
     *
     * @mbg.generated
     */
    public LocalDateTime getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_legal.modify_time
     *
     * @param modifyTime the value for t_cpy_legal.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_legal.data_resource
     *
     * @return the value of t_cpy_legal.data_resource
     *
     * @mbg.generated
     */
    public String getDataResource() {
        return dataResource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_legal.data_resource
     *
     * @param dataResource the value for t_cpy_legal.data_resource
     *
     * @mbg.generated
     */
    public void setDataResource(String dataResource) {
        this.dataResource = dataResource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_legal
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", companyId=").append(companyId);
        sb.append(", name=").append(name);
        sb.append(", post=").append(post);
        sb.append(", nationality=").append(nationality);
        sb.append(", sex=").append(sex);
        sb.append(", certificateType=").append(certificateType);
        sb.append(", certificateNumber=").append(certificateNumber);
        sb.append(", academic=").append(academic);
        sb.append(", degree=").append(degree);
        sb.append(", industryExperience=").append(industryExperience);
        sb.append(", managementExperience=").append(managementExperience);
        sb.append(", experience=").append(experience);
        sb.append(", qualificationName=").append(qualificationName);
        sb.append(", qualificationNo=").append(qualificationNo);
        sb.append(", technicalName=").append(technicalName);
        sb.append(", creditRecord=").append(creditRecord);
        sb.append(", startDate=").append(startDate);
        sb.append(", unit=").append(unit);
        sb.append(", graduateInstitutions=").append(graduateInstitutions);
        sb.append(", birthday=").append(birthday);
        sb.append(", marriage=").append(marriage);
        sb.append(", telephone=").append(telephone);
        sb.append(", postalAddress=").append(postalAddress);
        sb.append(", permanentAddress=").append(permanentAddress);
        sb.append(", joinTime=").append(joinTime);
        sb.append(", whethePartakeOperate=").append(whethePartakeOperate);
        sb.append(", personalCreditReport=").append(personalCreditReport);
        sb.append(", resume=").append(resume);
        sb.append(", createPerson=").append(createPerson);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyPerson=").append(modifyPerson);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", dataResource=").append(dataResource);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_legal
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TCpyLegal other = (TCpyLegal) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCompanyId() == null ? other.getCompanyId() == null : this.getCompanyId().equals(other.getCompanyId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getPost() == null ? other.getPost() == null : this.getPost().equals(other.getPost()))
            && (this.getNationality() == null ? other.getNationality() == null : this.getNationality().equals(other.getNationality()))
            && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
            && (this.getCertificateType() == null ? other.getCertificateType() == null : this.getCertificateType().equals(other.getCertificateType()))
            && (this.getCertificateNumber() == null ? other.getCertificateNumber() == null : this.getCertificateNumber().equals(other.getCertificateNumber()))
            && (this.getAcademic() == null ? other.getAcademic() == null : this.getAcademic().equals(other.getAcademic()))
            && (this.getDegree() == null ? other.getDegree() == null : this.getDegree().equals(other.getDegree()))
            && (this.getIndustryExperience() == null ? other.getIndustryExperience() == null : this.getIndustryExperience().equals(other.getIndustryExperience()))
            && (this.getManagementExperience() == null ? other.getManagementExperience() == null : this.getManagementExperience().equals(other.getManagementExperience()))
            && (this.getExperience() == null ? other.getExperience() == null : this.getExperience().equals(other.getExperience()))
            && (this.getQualificationName() == null ? other.getQualificationName() == null : this.getQualificationName().equals(other.getQualificationName()))
            && (this.getQualificationNo() == null ? other.getQualificationNo() == null : this.getQualificationNo().equals(other.getQualificationNo()))
            && (this.getTechnicalName() == null ? other.getTechnicalName() == null : this.getTechnicalName().equals(other.getTechnicalName()))
            && (this.getCreditRecord() == null ? other.getCreditRecord() == null : this.getCreditRecord().equals(other.getCreditRecord()))
            && (this.getStartDate() == null ? other.getStartDate() == null : this.getStartDate().equals(other.getStartDate()))
            && (this.getUnit() == null ? other.getUnit() == null : this.getUnit().equals(other.getUnit()))
            && (this.getGraduateInstitutions() == null ? other.getGraduateInstitutions() == null : this.getGraduateInstitutions().equals(other.getGraduateInstitutions()))
            && (this.getBirthday() == null ? other.getBirthday() == null : this.getBirthday().equals(other.getBirthday()))
            && (this.getMarriage() == null ? other.getMarriage() == null : this.getMarriage().equals(other.getMarriage()))
            && (this.getTelephone() == null ? other.getTelephone() == null : this.getTelephone().equals(other.getTelephone()))
            && (this.getPostalAddress() == null ? other.getPostalAddress() == null : this.getPostalAddress().equals(other.getPostalAddress()))
            && (this.getPermanentAddress() == null ? other.getPermanentAddress() == null : this.getPermanentAddress().equals(other.getPermanentAddress()))
            && (this.getJoinTime() == null ? other.getJoinTime() == null : this.getJoinTime().equals(other.getJoinTime()))
            && (this.getWhethePartakeOperate() == null ? other.getWhethePartakeOperate() == null : this.getWhethePartakeOperate().equals(other.getWhethePartakeOperate()))
            && (this.getPersonalCreditReport() == null ? other.getPersonalCreditReport() == null : this.getPersonalCreditReport().equals(other.getPersonalCreditReport()))
            && (this.getResume() == null ? other.getResume() == null : this.getResume().equals(other.getResume()))
            && (this.getCreatePerson() == null ? other.getCreatePerson() == null : this.getCreatePerson().equals(other.getCreatePerson()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getModifyPerson() == null ? other.getModifyPerson() == null : this.getModifyPerson().equals(other.getModifyPerson()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
            && (this.getDataResource() == null ? other.getDataResource() == null : this.getDataResource().equals(other.getDataResource()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_legal
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCompanyId() == null) ? 0 : getCompanyId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getPost() == null) ? 0 : getPost().hashCode());
        result = prime * result + ((getNationality() == null) ? 0 : getNationality().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getCertificateType() == null) ? 0 : getCertificateType().hashCode());
        result = prime * result + ((getCertificateNumber() == null) ? 0 : getCertificateNumber().hashCode());
        result = prime * result + ((getAcademic() == null) ? 0 : getAcademic().hashCode());
        result = prime * result + ((getDegree() == null) ? 0 : getDegree().hashCode());
        result = prime * result + ((getIndustryExperience() == null) ? 0 : getIndustryExperience().hashCode());
        result = prime * result + ((getManagementExperience() == null) ? 0 : getManagementExperience().hashCode());
        result = prime * result + ((getExperience() == null) ? 0 : getExperience().hashCode());
        result = prime * result + ((getQualificationName() == null) ? 0 : getQualificationName().hashCode());
        result = prime * result + ((getQualificationNo() == null) ? 0 : getQualificationNo().hashCode());
        result = prime * result + ((getTechnicalName() == null) ? 0 : getTechnicalName().hashCode());
        result = prime * result + ((getCreditRecord() == null) ? 0 : getCreditRecord().hashCode());
        result = prime * result + ((getStartDate() == null) ? 0 : getStartDate().hashCode());
        result = prime * result + ((getUnit() == null) ? 0 : getUnit().hashCode());
        result = prime * result + ((getGraduateInstitutions() == null) ? 0 : getGraduateInstitutions().hashCode());
        result = prime * result + ((getBirthday() == null) ? 0 : getBirthday().hashCode());
        result = prime * result + ((getMarriage() == null) ? 0 : getMarriage().hashCode());
        result = prime * result + ((getTelephone() == null) ? 0 : getTelephone().hashCode());
        result = prime * result + ((getPostalAddress() == null) ? 0 : getPostalAddress().hashCode());
        result = prime * result + ((getPermanentAddress() == null) ? 0 : getPermanentAddress().hashCode());
        result = prime * result + ((getJoinTime() == null) ? 0 : getJoinTime().hashCode());
        result = prime * result + ((getWhethePartakeOperate() == null) ? 0 : getWhethePartakeOperate().hashCode());
        result = prime * result + ((getPersonalCreditReport() == null) ? 0 : getPersonalCreditReport().hashCode());
        result = prime * result + ((getResume() == null) ? 0 : getResume().hashCode());
        result = prime * result + ((getCreatePerson() == null) ? 0 : getCreatePerson().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getModifyPerson() == null) ? 0 : getModifyPerson().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getDataResource() == null) ? 0 : getDataResource().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table t_cpy_legal
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        companyId("company_id", "companyId", "VARCHAR", false),
        name("name", "name", "VARCHAR", true),
        post("post", "post", "VARCHAR", false),
        nationality("nationality", "nationality", "VARCHAR", false),
        sex("sex", "sex", "VARCHAR", false),
        certificateType("certificate_type", "certificateType", "VARCHAR", false),
        certificateNumber("certificate_number", "certificateNumber", "VARCHAR", false),
        academic("academic", "academic", "VARCHAR", false),
        degree("degree", "degree", "VARCHAR", true),
        industryExperience("Industry_experience", "industryExperience", "VARCHAR", false),
        managementExperience("management_experience", "managementExperience", "VARCHAR", false),
        experience("experience", "experience", "VARCHAR", false),
        qualificationName("qualification_name", "qualificationName", "VARCHAR", false),
        qualificationNo("qualification_no", "qualificationNo", "VARCHAR", false),
        technicalName("technical_name", "technicalName", "VARCHAR", false),
        creditRecord("credit_record", "creditRecord", "VARCHAR", false),
        startDate("start_date", "startDate", "DATE", false),
        unit("unit", "unit", "VARCHAR", false),
        graduateInstitutions("graduate_institutions", "graduateInstitutions", "VARCHAR", false),
        birthday("birthday", "birthday", "DATE", false),
        marriage("marriage", "marriage", "VARCHAR", false),
        telephone("telephone", "telephone", "VARCHAR", false),
        postalAddress("postal_address", "postalAddress", "VARCHAR", false),
        permanentAddress("permanent_address", "permanentAddress", "VARCHAR", false),
        joinTime("join_time", "joinTime", "DATE", false),
        whethePartakeOperate("whethe_partake_operate", "whethePartakeOperate", "VARCHAR", false),
        personalCreditReport("personal_credit_report", "personalCreditReport", "VARCHAR", false),
        resume("resume", "resume", "VARCHAR", false),
        createPerson("create_person", "createPerson", "VARCHAR", false),
        createTime("create_time", "createTime", "TIMESTAMP", false),
        modifyPerson("modify_person", "modifyPerson", "VARCHAR", false),
        modifyTime("modify_time", "modifyTime", "TIMESTAMP", false),
        dataResource("data_resource", "dataResource", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_cpy_legal
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_cpy_legal
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_cpy_legal
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_cpy_legal
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_cpy_legal
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_cpy_legal
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_legal
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_legal
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_legal
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_legal
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_legal
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_legal
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_legal
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_legal
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_legal
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_legal
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}