package com.huizhi.supplier.db.model;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class TCpyShareholdersCapital {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_shareholders_capital.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_shareholders_capital.annual_report_id
     *
     * @mbg.generated
     */
    private String annualReportId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_shareholders_capital.shareholders
     *
     * @mbg.generated
     */
    private String shareholders;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_shareholders_capital.subscribed_capital_contribution
     *
     * @mbg.generated
     */
    private BigDecimal subscribedCapitalContribution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_shareholders_capital.subscribed_capital_time
     *
     * @mbg.generated
     */
    private LocalDate subscribedCapitalTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_shareholders_capital.subscribed_capital_way
     *
     * @mbg.generated
     */
    private String subscribedCapitalWay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_shareholders_capital.actual_capital_contribution
     *
     * @mbg.generated
     */
    private BigDecimal actualCapitalContribution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_shareholders_capital.actual_contribution_time
     *
     * @mbg.generated
     */
    private LocalDate actualContributionTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_shareholders_capital.create_person
     *
     * @mbg.generated
     */
    private String createPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_shareholders_capital.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_shareholders_capital.modify_person
     *
     * @mbg.generated
     */
    private String modifyPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_shareholders_capital.modify_time
     *
     * @mbg.generated
     */
    private LocalDateTime modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpy_shareholders_capital.data_resource
     *
     * @mbg.generated
     */
    private String dataResource;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_shareholders_capital.id
     *
     * @return the value of t_cpy_shareholders_capital.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_shareholders_capital.id
     *
     * @param id the value for t_cpy_shareholders_capital.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_shareholders_capital.annual_report_id
     *
     * @return the value of t_cpy_shareholders_capital.annual_report_id
     *
     * @mbg.generated
     */
    public String getAnnualReportId() {
        return annualReportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_shareholders_capital.annual_report_id
     *
     * @param annualReportId the value for t_cpy_shareholders_capital.annual_report_id
     *
     * @mbg.generated
     */
    public void setAnnualReportId(String annualReportId) {
        this.annualReportId = annualReportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_shareholders_capital.shareholders
     *
     * @return the value of t_cpy_shareholders_capital.shareholders
     *
     * @mbg.generated
     */
    public String getShareholders() {
        return shareholders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_shareholders_capital.shareholders
     *
     * @param shareholders the value for t_cpy_shareholders_capital.shareholders
     *
     * @mbg.generated
     */
    public void setShareholders(String shareholders) {
        this.shareholders = shareholders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_shareholders_capital.subscribed_capital_contribution
     *
     * @return the value of t_cpy_shareholders_capital.subscribed_capital_contribution
     *
     * @mbg.generated
     */
    public BigDecimal getSubscribedCapitalContribution() {
        return subscribedCapitalContribution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_shareholders_capital.subscribed_capital_contribution
     *
     * @param subscribedCapitalContribution the value for t_cpy_shareholders_capital.subscribed_capital_contribution
     *
     * @mbg.generated
     */
    public void setSubscribedCapitalContribution(BigDecimal subscribedCapitalContribution) {
        this.subscribedCapitalContribution = subscribedCapitalContribution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_shareholders_capital.subscribed_capital_time
     *
     * @return the value of t_cpy_shareholders_capital.subscribed_capital_time
     *
     * @mbg.generated
     */
    public LocalDate getSubscribedCapitalTime() {
        return subscribedCapitalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_shareholders_capital.subscribed_capital_time
     *
     * @param subscribedCapitalTime the value for t_cpy_shareholders_capital.subscribed_capital_time
     *
     * @mbg.generated
     */
    public void setSubscribedCapitalTime(LocalDate subscribedCapitalTime) {
        this.subscribedCapitalTime = subscribedCapitalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_shareholders_capital.subscribed_capital_way
     *
     * @return the value of t_cpy_shareholders_capital.subscribed_capital_way
     *
     * @mbg.generated
     */
    public String getSubscribedCapitalWay() {
        return subscribedCapitalWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_shareholders_capital.subscribed_capital_way
     *
     * @param subscribedCapitalWay the value for t_cpy_shareholders_capital.subscribed_capital_way
     *
     * @mbg.generated
     */
    public void setSubscribedCapitalWay(String subscribedCapitalWay) {
        this.subscribedCapitalWay = subscribedCapitalWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_shareholders_capital.actual_capital_contribution
     *
     * @return the value of t_cpy_shareholders_capital.actual_capital_contribution
     *
     * @mbg.generated
     */
    public BigDecimal getActualCapitalContribution() {
        return actualCapitalContribution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_shareholders_capital.actual_capital_contribution
     *
     * @param actualCapitalContribution the value for t_cpy_shareholders_capital.actual_capital_contribution
     *
     * @mbg.generated
     */
    public void setActualCapitalContribution(BigDecimal actualCapitalContribution) {
        this.actualCapitalContribution = actualCapitalContribution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_shareholders_capital.actual_contribution_time
     *
     * @return the value of t_cpy_shareholders_capital.actual_contribution_time
     *
     * @mbg.generated
     */
    public LocalDate getActualContributionTime() {
        return actualContributionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_shareholders_capital.actual_contribution_time
     *
     * @param actualContributionTime the value for t_cpy_shareholders_capital.actual_contribution_time
     *
     * @mbg.generated
     */
    public void setActualContributionTime(LocalDate actualContributionTime) {
        this.actualContributionTime = actualContributionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_shareholders_capital.create_person
     *
     * @return the value of t_cpy_shareholders_capital.create_person
     *
     * @mbg.generated
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_shareholders_capital.create_person
     *
     * @param createPerson the value for t_cpy_shareholders_capital.create_person
     *
     * @mbg.generated
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_shareholders_capital.create_time
     *
     * @return the value of t_cpy_shareholders_capital.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_shareholders_capital.create_time
     *
     * @param createTime the value for t_cpy_shareholders_capital.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_shareholders_capital.modify_person
     *
     * @return the value of t_cpy_shareholders_capital.modify_person
     *
     * @mbg.generated
     */
    public String getModifyPerson() {
        return modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_shareholders_capital.modify_person
     *
     * @param modifyPerson the value for t_cpy_shareholders_capital.modify_person
     *
     * @mbg.generated
     */
    public void setModifyPerson(String modifyPerson) {
        this.modifyPerson = modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_shareholders_capital.modify_time
     *
     * @return the value of t_cpy_shareholders_capital.modify_time
     *
     * @mbg.generated
     */
    public LocalDateTime getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_shareholders_capital.modify_time
     *
     * @param modifyTime the value for t_cpy_shareholders_capital.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpy_shareholders_capital.data_resource
     *
     * @return the value of t_cpy_shareholders_capital.data_resource
     *
     * @mbg.generated
     */
    public String getDataResource() {
        return dataResource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpy_shareholders_capital.data_resource
     *
     * @param dataResource the value for t_cpy_shareholders_capital.data_resource
     *
     * @mbg.generated
     */
    public void setDataResource(String dataResource) {
        this.dataResource = dataResource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_shareholders_capital
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", annualReportId=").append(annualReportId);
        sb.append(", shareholders=").append(shareholders);
        sb.append(", subscribedCapitalContribution=").append(subscribedCapitalContribution);
        sb.append(", subscribedCapitalTime=").append(subscribedCapitalTime);
        sb.append(", subscribedCapitalWay=").append(subscribedCapitalWay);
        sb.append(", actualCapitalContribution=").append(actualCapitalContribution);
        sb.append(", actualContributionTime=").append(actualContributionTime);
        sb.append(", createPerson=").append(createPerson);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyPerson=").append(modifyPerson);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", dataResource=").append(dataResource);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_shareholders_capital
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TCpyShareholdersCapital other = (TCpyShareholdersCapital) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAnnualReportId() == null ? other.getAnnualReportId() == null : this.getAnnualReportId().equals(other.getAnnualReportId()))
            && (this.getShareholders() == null ? other.getShareholders() == null : this.getShareholders().equals(other.getShareholders()))
            && (this.getSubscribedCapitalContribution() == null ? other.getSubscribedCapitalContribution() == null : this.getSubscribedCapitalContribution().equals(other.getSubscribedCapitalContribution()))
            && (this.getSubscribedCapitalTime() == null ? other.getSubscribedCapitalTime() == null : this.getSubscribedCapitalTime().equals(other.getSubscribedCapitalTime()))
            && (this.getSubscribedCapitalWay() == null ? other.getSubscribedCapitalWay() == null : this.getSubscribedCapitalWay().equals(other.getSubscribedCapitalWay()))
            && (this.getActualCapitalContribution() == null ? other.getActualCapitalContribution() == null : this.getActualCapitalContribution().equals(other.getActualCapitalContribution()))
            && (this.getActualContributionTime() == null ? other.getActualContributionTime() == null : this.getActualContributionTime().equals(other.getActualContributionTime()))
            && (this.getCreatePerson() == null ? other.getCreatePerson() == null : this.getCreatePerson().equals(other.getCreatePerson()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getModifyPerson() == null ? other.getModifyPerson() == null : this.getModifyPerson().equals(other.getModifyPerson()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
            && (this.getDataResource() == null ? other.getDataResource() == null : this.getDataResource().equals(other.getDataResource()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpy_shareholders_capital
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAnnualReportId() == null) ? 0 : getAnnualReportId().hashCode());
        result = prime * result + ((getShareholders() == null) ? 0 : getShareholders().hashCode());
        result = prime * result + ((getSubscribedCapitalContribution() == null) ? 0 : getSubscribedCapitalContribution().hashCode());
        result = prime * result + ((getSubscribedCapitalTime() == null) ? 0 : getSubscribedCapitalTime().hashCode());
        result = prime * result + ((getSubscribedCapitalWay() == null) ? 0 : getSubscribedCapitalWay().hashCode());
        result = prime * result + ((getActualCapitalContribution() == null) ? 0 : getActualCapitalContribution().hashCode());
        result = prime * result + ((getActualContributionTime() == null) ? 0 : getActualContributionTime().hashCode());
        result = prime * result + ((getCreatePerson() == null) ? 0 : getCreatePerson().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getModifyPerson() == null) ? 0 : getModifyPerson().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getDataResource() == null) ? 0 : getDataResource().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table t_cpy_shareholders_capital
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        annualReportId("annual_report_id", "annualReportId", "VARCHAR", false),
        shareholders("shareholders", "shareholders", "VARCHAR", false),
        subscribedCapitalContribution("subscribed_capital_contribution", "subscribedCapitalContribution", "DECIMAL", false),
        subscribedCapitalTime("subscribed_capital_time", "subscribedCapitalTime", "DATE", false),
        subscribedCapitalWay("subscribed_capital_way", "subscribedCapitalWay", "VARCHAR", false),
        actualCapitalContribution("actual_capital_contribution", "actualCapitalContribution", "DECIMAL", false),
        actualContributionTime("actual_contribution_time", "actualContributionTime", "DATE", false),
        createPerson("create_person", "createPerson", "VARCHAR", false),
        createTime("create_time", "createTime", "TIMESTAMP", false),
        modifyPerson("modify_person", "modifyPerson", "VARCHAR", false),
        modifyTime("modify_time", "modifyTime", "TIMESTAMP", false),
        dataResource("data_resource", "dataResource", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_cpy_shareholders_capital
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_cpy_shareholders_capital
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_cpy_shareholders_capital
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_cpy_shareholders_capital
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_cpy_shareholders_capital
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_cpy_shareholders_capital
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_shareholders_capital
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_shareholders_capital
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_shareholders_capital
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_shareholders_capital
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_shareholders_capital
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_shareholders_capital
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_shareholders_capital
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_shareholders_capital
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_shareholders_capital
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_cpy_shareholders_capital
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}