package com.huizhi.supplier.db.model;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class TPerEvalInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_per_eval_info.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_per_eval_info.cont_code
     *
     * @mbg.generated
     */
    private String contCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_per_eval_info.title_code
     *
     * @mbg.generated
     */
    private String titleCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_per_eval_info.content_code
     *
     * @mbg.generated
     */
    private String contentCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_per_eval_info.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_per_eval_info.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_per_eval_info.create_date
     *
     * @mbg.generated
     */
    private LocalDateTime createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_per_eval_info.id
     *
     * @return the value of t_per_eval_info.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_per_eval_info.id
     *
     * @param id the value for t_per_eval_info.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_per_eval_info.cont_code
     *
     * @return the value of t_per_eval_info.cont_code
     *
     * @mbg.generated
     */
    public String getContCode() {
        return contCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_per_eval_info.cont_code
     *
     * @param contCode the value for t_per_eval_info.cont_code
     *
     * @mbg.generated
     */
    public void setContCode(String contCode) {
        this.contCode = contCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_per_eval_info.title_code
     *
     * @return the value of t_per_eval_info.title_code
     *
     * @mbg.generated
     */
    public String getTitleCode() {
        return titleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_per_eval_info.title_code
     *
     * @param titleCode the value for t_per_eval_info.title_code
     *
     * @mbg.generated
     */
    public void setTitleCode(String titleCode) {
        this.titleCode = titleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_per_eval_info.content_code
     *
     * @return the value of t_per_eval_info.content_code
     *
     * @mbg.generated
     */
    public String getContentCode() {
        return contentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_per_eval_info.content_code
     *
     * @param contentCode the value for t_per_eval_info.content_code
     *
     * @mbg.generated
     */
    public void setContentCode(String contentCode) {
        this.contentCode = contentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_per_eval_info.user_id
     *
     * @return the value of t_per_eval_info.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_per_eval_info.user_id
     *
     * @param userId the value for t_per_eval_info.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_per_eval_info.user_name
     *
     * @return the value of t_per_eval_info.user_name
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_per_eval_info.user_name
     *
     * @param userName the value for t_per_eval_info.user_name
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_per_eval_info.create_date
     *
     * @return the value of t_per_eval_info.create_date
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_per_eval_info.create_date
     *
     * @param createDate the value for t_per_eval_info.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_per_eval_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", contCode=").append(contCode);
        sb.append(", titleCode=").append(titleCode);
        sb.append(", contentCode=").append(contentCode);
        sb.append(", userId=").append(userId);
        sb.append(", userName=").append(userName);
        sb.append(", createDate=").append(createDate);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_per_eval_info
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TPerEvalInfo other = (TPerEvalInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getContCode() == null ? other.getContCode() == null : this.getContCode().equals(other.getContCode()))
            && (this.getTitleCode() == null ? other.getTitleCode() == null : this.getTitleCode().equals(other.getTitleCode()))
            && (this.getContentCode() == null ? other.getContentCode() == null : this.getContentCode().equals(other.getContentCode()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_per_eval_info
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getContCode() == null) ? 0 : getContCode().hashCode());
        result = prime * result + ((getTitleCode() == null) ? 0 : getTitleCode().hashCode());
        result = prime * result + ((getContentCode() == null) ? 0 : getContentCode().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table t_per_eval_info
     *
     * @mbg.generated
     */
    public enum Column {
        id("id", "id", "INTEGER", false),
        contCode("cont_code", "contCode", "VARCHAR", false),
        titleCode("title_code", "titleCode", "VARCHAR", false),
        contentCode("content_code", "contentCode", "CHAR", false),
        userId("user_id", "userId", "INTEGER", false),
        userName("user_name", "userName", "VARCHAR", false),
        createDate("create_date", "createDate", "TIMESTAMP", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_per_eval_info
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_per_eval_info
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_per_eval_info
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_per_eval_info
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_per_eval_info
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_per_eval_info
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_per_eval_info
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_per_eval_info
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_per_eval_info
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_per_eval_info
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_per_eval_info
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_per_eval_info
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_per_eval_info
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_per_eval_info
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_per_eval_info
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_per_eval_info
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}